2018/12/03 11:20:21 [error] 196380#109644: *30 CreateFile() "E:\work\nginx-1.9.1/html/favicon.ico" failed (2: The system cannot find the file specified), client: 127.0.0.1, server: localhost, request: "GET /favicon.ico HTTP/1.1", host: "127.0.0.1"
2018/12/03 18:17:01 [error] 196380#109644: *143 CreateFile() "E:\work\nginx-1.9.1/html/favicon.ico" failed (2: The system cannot find the file specified), client: 127.0.0.1, server: localhost, request: "GET /favicon.ico HTTP/1.1", host: "127.0.0.1"
2018/12/04 20:28:44 [error] 196380#109644: *879 WSARecv() failed (10054: An existing connection was forcibly closed by the remote host) while reading response header from upstream, client: 127.0.0.1, server: localhost, request: "GET /cdn/api/param/user HTTP/1.1", upstream: "http://127.0.0.1:5000/cdn/api/param/user", host: "127.0.0.1", referrer: "http://127.0.0.1/cdn/static/create"
2018/12/05 17:32:03 [error] 196380#109644: *973 upstream timed out (10060: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond) while connecting to upstream, client: 127.0.0.1, server: localhost, request: "GET /cdn/api/order/task/?pageindex=1&pagesize=10 HTTP/1.1", upstream: "http://127.0.0.1:5000/cdn/api/order/task/?pageindex=1&pagesize=10", host: "127.0.0.1", referrer: "http://127.0.0.1/cdn/static/task"
2018/12/05 19:48:42 [error] 196380#109644: *1284 upstream timed out (10060: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond) while connecting to upstream, client: 127.0.0.1, server: localhost, request: "GET /cdn/api/order/task/?pageindex=1&pagesize=10 HTTP/1.1", upstream: "http://127.0.0.1:5000/cdn/api/order/task/?pageindex=1&pagesize=10", host: "127.0.0.1", referrer: "http://127.0.0.1/cdn/static/task"
2018/12/06 15:50:56 [error] 196380#109644: *1874 upstream timed out (10060: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond) while connecting to upstream, client: 127.0.0.1, server: localhost, request: "GET /cdn/api/order/task/?pageindex=1&pagesize=10 HTTP/1.1", upstream: "http://127.0.0.1:5000/cdn/api/order/task/?pageindex=1&pagesize=10", host: "127.0.0.1", referrer: "http://127.0.0.1/cdn/static/task"
2018/12/06 15:59:06 [error] 196380#109644: *1887 upstream timed out (10060: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond) while connecting to upstream, client: 127.0.0.1, server: localhost, request: "GET /cdn/api/order/task/?pageindex=1&pagesize=10 HTTP/1.1", upstream: "http://127.0.0.1:5000/cdn/api/order/task/?pageindex=1&pagesize=10", host: "127.0.0.1", referrer: "http://127.0.0.1/cdn/static/task"
2018/12/07 18:48:20 [error] 196380#109644: *2896 upstream timed out (10060: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond) while connecting to upstream, client: 127.0.0.1, server: localhost, request: "GET /cdn/api/order/task/?pageindex=1&pagesize=10 HTTP/1.1", upstream: "http://127.0.0.1:5000/cdn/api/order/task/?pageindex=1&pagesize=10", host: "127.0.0.1", referrer: "http://127.0.0.1/cdn/static/task"
2018/12/11 14:24:05 [error] 196380#109644: *3371 CreateFile() "E:\work\nginx-1.9.1/html/favicon.ico" failed (2: The system cannot find the file specified), client: 127.0.0.1, server: localhost, request: "GET /favicon.ico HTTP/1.1", host: "127.0.0.1", referrer: "http://127.0.0.1/cdn/opapi/order/task/13696/detail"
2018/12/11 15:34:37 [error] 196380#109644: *3433 upstream timed out (10060: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond) while connecting to upstream, client: 127.0.0.1, server: localhost, request: "GET /cdn/api/order/task/?pageindex=1&pagesize=10 HTTP/1.1", upstream: "http://127.0.0.1:5000/cdn/api/order/task/?pageindex=1&pagesize=10", host: "127.0.0.1", referrer: "http://127.0.0.1/cdn/static/task"
2018/12/13 14:33:14 [error] 196380#109644: *4700 WSARecv() failed (10054: An existing connection was forcibly closed by the remote host) while reading response header from upstream, client: 127.0.0.1, server: localhost, request: "GET /cdn/api/order/task/?pageindex=1&pagesize=10 HTTP/1.1", upstream: "http://127.0.0.1:5000/cdn/api/order/task/?pageindex=1&pagesize=10", host: "127.0.0.1", referrer: "http://127.0.0.1/cdn/static/task"
2018/12/13 15:18:19 [error] 196380#109644: *4706 upstream timed out (10060: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond) while connecting to upstream, client: 127.0.0.1, server: localhost, request: "GET /cdn/api/order/task/?pageindex=1&pagesize=10 HTTP/1.1", upstream: "http://127.0.0.1:5000/cdn/api/order/task/?pageindex=1&pagesize=10", host: "127.0.0.1", referrer: "http://127.0.0.1/cdn/static/task"
2018/12/13 15:48:48 [error] 196380#109644: *4710 upstream timed out (10060: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond) while connecting to upstream, client: 127.0.0.1, server: localhost, request: "GET /cdn/api/order/task/?pageindex=1&pagesize=10 HTTP/1.1", upstream: "http://127.0.0.1:5000/cdn/api/order/task/?pageindex=1&pagesize=10", host: "127.0.0.1", referrer: "http://127.0.0.1/cdn/static/task"
2018/12/13 16:19:37 [error] 196380#109644: *4714 upstream timed out (10060: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond) while connecting to upstream, client: 127.0.0.1, server: localhost, request: "GET /cdn/api/order/task/?pageindex=1&pagesize=10 HTTP/1.1", upstream: "http://127.0.0.1:5000/cdn/api/order/task/?pageindex=1&pagesize=10", host: "127.0.0.1", referrer: "http://127.0.0.1/cdn/static/task"
2018/12/13 16:35:08 [error] 196380#109644: *4716 upstream timed out (10060: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond) while connecting to upstream, client: 127.0.0.1, server: localhost, request: "GET /cdn/api/order/task/?pageindex=1&pagesize=10 HTTP/1.1", upstream: "http://127.0.0.1:5000/cdn/api/order/task/?pageindex=1&pagesize=10", host: "127.0.0.1", referrer: "http://127.0.0.1/cdn/static/task"
2018/12/13 19:23:42 [error] 196380#109644: *5219 upstream timed out (10060: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond) while connecting to upstream, client: 127.0.0.1, server: localhost, request: "GET /cdn/api/order/task/?pageindex=1&pagesize=10 HTTP/1.1", upstream: "http://127.0.0.1:5000/cdn/api/order/task/?pageindex=1&pagesize=10", host: "127.0.0.1", referrer: "http://127.0.0.1/cdn/static/task"
2018/12/14 15:24:23 [error] 196380#109644: *5904 WSARecv() failed (10054: An existing connection was forcibly closed by the remote host) while reading response header from upstream, client: 127.0.0.1, server: localhost, request: "GET /cdn/api/order/task/?pageindex=1&pagesize=10 HTTP/1.1", upstream: "http://127.0.0.1:5000/cdn/api/order/task/?pageindex=1&pagesize=10", host: "127.0.0.1", referrer: "http://127.0.0.1/cdn/static/task"
2018/12/18 11:55:12 [error] 196380#109644: *6215 upstream timed out (10060: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond) while connecting to upstream, client: 127.0.0.1, server: localhost, request: "GET /cdn/api/cache?pageindex=1&pagesize=20 HTTP/1.1", upstream: "http://127.0.0.1:5000/cdn/api/cache?pageindex=1&pagesize=20", host: "127.0.0.1", referrer: "http://127.0.0.1/cdn/static/"
2018/12/18 18:15:25 [error] 196380#109644: *6322 WSARecv() failed (10054: An existing connection was forcibly closed by the remote host) while reading response header from upstream, client: 127.0.0.1, server: localhost, request: "POST /cdn/api/report/ HTTP/1.1", upstream: "http://127.0.0.1:5000/cdn/api/report/", host: "127.0.0.1", referrer: "http://127.0.0.1/cdn/static/report/quantity"
2018/12/18 18:17:22 [error] 196380#109644: *6324 WSARecv() failed (10054: An existing connection was forcibly closed by the remote host) while reading response header from upstream, client: 127.0.0.1, server: localhost, request: "POST /cdn/api/report/ HTTP/1.1", upstream: "http://127.0.0.1:5000/cdn/api/report/", host: "127.0.0.1", referrer: "http://127.0.0.1/cdn/static/report/quantity"
2018/12/18 18:17:39 [error] 196380#109644: *6326 WSARecv() failed (10054: An existing connection was forcibly closed by the remote host) while reading response header from upstream, client: 127.0.0.1, server: localhost, request: "POST /cdn/api/report/ HTTP/1.1", upstream: "http://127.0.0.1:5000/cdn/api/report/", host: "127.0.0.1", referrer: "http://127.0.0.1/cdn/static/report/quantity"
2018/12/18 18:18:27 [error] 196380#109644: *6328 WSARecv() failed (10054: An existing connection was forcibly closed by the remote host) while reading response header from upstream, client: 127.0.0.1, server: localhost, request: "POST /cdn/api/report/ HTTP/1.1", upstream: "http://127.0.0.1:5000/cdn/api/report/", host: "127.0.0.1", referrer: "http://127.0.0.1/cdn/static/report/quantity"
2018/12/18 18:19:18 [error] 196380#109644: *6330 WSARecv() failed (10054: An existing connection was forcibly closed by the remote host) while reading response header from upstream, client: 127.0.0.1, server: localhost, request: "POST /cdn/api/report/ HTTP/1.1", upstream: "http://127.0.0.1:5000/cdn/api/report/", host: "127.0.0.1", referrer: "http://127.0.0.1/cdn/static/report/quantity"
2018/12/18 18:42:48 [error] 196380#109644: *6363 WSARecv() failed (10054: An existing connection was forcibly closed by the remote host) while reading response header from upstream, client: 127.0.0.1, server: localhost, request: "POST /cdn/api/report/ HTTP/1.1", upstream: "http://127.0.0.1:5000/cdn/api/report/", host: "127.0.0.1", referrer: "http://127.0.0.1/cdn/static/report/quantity"
2018/12/18 18:43:08 [error] 196380#109644: *6363 WSARecv() failed (10054: An existing connection was forcibly closed by the remote host) while reading response header from upstream, client: 127.0.0.1, server: localhost, request: "POST /cdn/api/report/ HTTP/1.1", upstream: "http://127.0.0.1:5000/cdn/api/report/", host: "127.0.0.1", referrer: "http://127.0.0.1/cdn/static/report/quantity"
2018/12/18 19:48:58 [error] 196380#109644: *6370 WSARecv() failed (10054: An existing connection was forcibly closed by the remote host) while reading response header from upstream, client: 127.0.0.1, server: localhost, request: "GET /cdn/api/param/user HTTP/1.1", upstream: "http://127.0.0.1:5000/cdn/api/param/user", host: "127.0.0.1", referrer: "http://127.0.0.1/cdn/static/report/quantity"
2018/12/18 19:49:23 [error] 196380#109644: *6381 WSARecv() failed (10054: An existing connection was forcibly closed by the remote host) while reading response header from upstream, client: 127.0.0.1, server: localhost, request: "POST /cdn/api/report/ HTTP/1.1", upstream: "http://127.0.0.1:5000/cdn/api/report/", host: "127.0.0.1", referrer: "http://127.0.0.1/cdn/static/report/quantity?token=7da8af7f844b67072ff45eae8b3e805552a0e51bab952497708547c5e170b941&lang=cn"
2018/12/18 20:03:04 [error] 196380#109644: *6403 WSARecv() failed (10054: An existing connection was forcibly closed by the remote host) while reading response header from upstream, client: 127.0.0.1, server: localhost, request: "POST /cdn/api/report/ HTTP/1.1", upstream: "http://127.0.0.1:5000/cdn/api/report/", host: "127.0.0.1", referrer: "http://127.0.0.1/cdn/static/report/quantity?token=7da8af7f844b67072ff45eae8b3e805552a0e51bab952497708547c5e170b941&lang=cn"
2018/12/18 20:03:50 [error] 196380#109644: *6405 WSARecv() failed (10054: An existing connection was forcibly closed by the remote host) while reading response header from upstream, client: 127.0.0.1, server: localhost, request: "POST /cdn/api/report/ HTTP/1.1", upstream: "http://127.0.0.1:5000/cdn/api/report/", host: "127.0.0.1", referrer: "http://127.0.0.1/cdn/static/report/quantity?token=7da8af7f844b67072ff45eae8b3e805552a0e51bab952497708547c5e170b941&lang=cn"
2018/12/18 20:04:28 [error] 196380#109644: *6407 WSARecv() failed (10054: An existing connection was forcibly closed by the remote host) while reading response header from upstream, client: 127.0.0.1, server: localhost, request: "POST /cdn/api/report/ HTTP/1.1", upstream: "http://127.0.0.1:5000/cdn/api/report/", host: "127.0.0.1", referrer: "http://127.0.0.1/cdn/static/report/quantity?token=7da8af7f844b67072ff45eae8b3e805552a0e51bab952497708547c5e170b941&lang=cn"
2019/01/17 03:38:40 [error] 13276#5420: *1028 CreateFile() "E:\work\nginx-1.9.1/html/favicon.ico" failed (2: The system cannot find the file specified), client: 127.0.0.1, server: localhost, request: "GET /favicon.ico HTTP/1.1", host: "127.0.0.1", referrer: "http://127.0.0.1/dns/static/"
2019/01/22 19:08:59 [error] 13276#5420: *2436 WSARecv() failed (10054: An existing connection was forcibly closed by the remote host) while reading response header from upstream, client: 127.0.0.1, server: localhost, request: "GET /cdn/api/order/task/?pageindex=1&pagesize=10 HTTP/1.1", upstream: "http://127.0.0.1:5000/cdn/api/order/task/?pageindex=1&pagesize=10", host: "127.0.0.1", referrer: "http://127.0.0.1/cdn/static/task"
2019/01/22 19:12:32 [error] 13276#5420: *2436 upstream timed out (10060: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond) while connecting to upstream, client: 127.0.0.1, server: localhost, request: "GET /cdn/api/order/task/?pageindex=1&pagesize=10 HTTP/1.1", upstream: "http://127.0.0.1:5000/cdn/api/order/task/?pageindex=1&pagesize=10", host: "127.0.0.1", referrer: "http://127.0.0.1/cdn/static/task"
2019/01/24 11:01:08 [error] 8484#5912: *4 CreateFile() "E:\work\nginx-1.9.1/html/favicon.ico" failed (2: The system cannot find the file specified), client: 127.0.0.1, server: localhost, request: "GET /favicon.ico HTTP/1.1", host: "127.0.0.1", referrer: "http://127.0.0.1/dns/static/"
2019/02/15 10:52:06 [error] 3584#3256: *225 CreateFile() "E:\work\nginx-1.9.1/html/favicon.ico" failed (2: The system cannot find the file specified), client: 127.0.0.1, server: localhost, request: "GET /favicon.ico HTTP/1.1", host: "127.0.0.1"
2019/02/19 18:10:34 [error] 3584#3256: *350 CreateFile() "E:\work\nginx-1.9.1/html/v.gif" failed (2: The system cannot find the file specified), client: 127.0.0.1, server: localhost, request: "GET /v.gif?pid=201&pj=www&fm=hide&p1=3&mu=http://top.baidu.com/buzz?b=1&rsv_stl=0&rsv_srcid=20811&p5=3&rsv_tpl=right_toplist1&qid=99cb7875000b38fc&tab=baidu_rightheightadjust&path=http%3A%2F%2Fwww.baidu.com%2Fs%3Fie%3Dutf-8%26f%3D8%26rsv_bp%3D0%26rsv_idx%3D1%26tn%3Dbaidu%26wd%3D1%25E7%25A7%2592%25E7%25AD%2589%25E4%25BA%258E%25E5%25A4%259A%25E5%25B0%2591%25E6%25AF%25AB%25E7%25A7%2592%26rsv_pq%3D95fa535e00066b12%26rsv_t%3D9497Zh1JxCmkjAzrQ7P0ErqB4xeUOigGRBgy%252FvtNd0cDEYE3uCIFUh%252FhsLw%26rqlang%3Dcn%26rsv_enter%3D1%26rsv_sug3%3D4%26rsv_sug1%3D4%26rsv_sug7%3D100&wd=lodash&rsv_sid=1429_21078_26350&rsv_did=0ef642305dd2f8626fd89da445ef803f&t=1550571033983 HTTP/1.1", host: "nsclick.baidu.com", referrer: "http://www.baidu.com/s?ie=utf-8&f=8&rsv_bp=0&rsv_idx=1&tn=baidu&wd=1%E7%A7%92%E7%AD%89%E4%BA%8E%E5%A4%9A%E5%B0%91%E6%AF%AB%E7%A7%92&rsv_pq=95fa535e00066b12&rsv_t=9497Zh1JxCmkjAzrQ7P0ErqB4xeUOigGRBgy%2FvtNd0cDEYE3uCIFUh%2FhsLw&rqlang=cn&rsv_enter=1&rsv_sug3=4&rsv_sug1=4&rsv_sug7=100"
2019/02/25 19:31:10 [error] 5564#23236: *1 rewrite or internal redirection cycle while internally redirecting to "/cdn/admin/", client: 127.0.0.1, server: localhost, request: "GET /cdn/admin/zdnsresolution HTTP/1.1", host: "127.0.0.1"
2019/02/25 19:31:10 [error] 5564#23236: *2 CreateFile() "E:\work\nginx-1.9.1/html/favicon.ico" failed (2: The system cannot find the file specified), client: 127.0.0.1, server: localhost, request: "GET /favicon.ico HTTP/1.1", host: "127.0.0.1", referrer: "http://127.0.0.1/cdn/admin/zdnsresolution"
2019/02/28 18:36:27 [error] 10648#13864: *445 WSARecv() failed (10054: An existing connection was forcibly closed by the remote host) while reading response header from upstream, client: 127.0.0.1, server: localhost, request: "GET /cdn/opapi/speed/?pageindex=1&pagesize=20 HTTP/1.1", upstream: "http://127.0.0.1:5001/cdn/opapi/speed/?pageindex=1&pagesize=20", host: "127.0.0.1", referrer: "http://127.0.0.1/cdn/admin/zdnsresolution"
2019/02/28 18:36:27 [error] 10648#13864: *447 WSARecv() failed (10054: An existing connection was forcibly closed by the remote host) while reading response header from upstream, client: 127.0.0.1, server: localhost, request: "GET /cdn/opapi/resolve?pageindex=1&pagesize=20 HTTP/1.1", upstream: "http://127.0.0.1:5001/cdn/opapi/resolve?pageindex=1&pagesize=20", host: "127.0.0.1", referrer: "http://127.0.0.1/cdn/admin/"
2019/03/07 12:11:20 [error] 10648#13864: *1286 upstream timed out (10060: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond) while connecting to upstream, client: 127.0.0.1, server: localhost, request: "GET /cdn/api/order/task/?pageindex=1&pagesize=10 HTTP/1.1", upstream: "http://127.0.0.1:5000/cdn/api/order/task/?pageindex=1&pagesize=10", host: "127.0.0.1", referrer: "http://127.0.0.1/cdn/static/task"
2019/03/07 12:14:37 [error] 10648#13864: *1288 upstream timed out (10060: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond) while connecting to upstream, client: 127.0.0.1, server: localhost, request: "GET /cdn/api/order/task/?pageindex=1&pagesize=10 HTTP/1.1", upstream: "http://127.0.0.1:5000/cdn/api/order/task/?pageindex=1&pagesize=10", host: "127.0.0.1", referrer: "http://127.0.0.1/cdn/static/task"
2019/03/07 12:17:59 [error] 10648#13864: *1290 upstream timed out (10060: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond) while connecting to upstream, client: 127.0.0.1, server: localhost, request: "GET /cdn/api/order/task/?pageindex=1&pagesize=10 HTTP/1.1", upstream: "http://127.0.0.1:5000/cdn/api/order/task/?pageindex=1&pagesize=10", host: "127.0.0.1", referrer: "http://127.0.0.1/cdn/static/task"
2019/03/07 12:21:25 [error] 10648#13864: *1292 upstream timed out (10060: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond) while connecting to upstream, client: 127.0.0.1, server: localhost, request: "GET /cdn/api/order/task/?pageindex=1&pagesize=10 HTTP/1.1", upstream: "http://127.0.0.1:5000/cdn/api/order/task/?pageindex=1&pagesize=10", host: "127.0.0.1", referrer: "http://127.0.0.1/cdn/static/task"
2019/03/07 12:28:33 [error] 10648#13864: *1296 upstream timed out (10060: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond) while connecting to upstream, client: 127.0.0.1, server: localhost, request: "GET /cdn/api/order/task/?pageindex=1&pagesize=10 HTTP/1.1", upstream: "http://127.0.0.1:5000/cdn/api/order/task/?pageindex=1&pagesize=10", host: "127.0.0.1", referrer: "http://127.0.0.1/cdn/static/task"
2019/03/07 12:32:14 [error] 10648#13864: *1298 upstream timed out (10060: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond) while connecting to upstream, client: 127.0.0.1, server: localhost, request: "GET /cdn/api/order/task/?pageindex=1&pagesize=10 HTTP/1.1", upstream: "http://127.0.0.1:5000/cdn/api/order/task/?pageindex=1&pagesize=10", host: "127.0.0.1", referrer: "http://127.0.0.1/cdn/static/task"
2019/03/07 12:36:01 [error] 10648#13864: *1300 upstream timed out (10060: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond) while connecting to upstream, client: 127.0.0.1, server: localhost, request: "GET /cdn/api/order/task/?pageindex=1&pagesize=10 HTTP/1.1", upstream: "http://127.0.0.1:5000/cdn/api/order/task/?pageindex=1&pagesize=10", host: "127.0.0.1", referrer: "http://127.0.0.1/cdn/static/task"
2019/03/07 12:39:52 [error] 10648#13864: *1302 upstream timed out (10060: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond) while connecting to upstream, client: 127.0.0.1, server: localhost, request: "GET /cdn/api/order/task/?pageindex=1&pagesize=10 HTTP/1.1", upstream: "http://127.0.0.1:5000/cdn/api/order/task/?pageindex=1&pagesize=10", host: "127.0.0.1", referrer: "http://127.0.0.1/cdn/static/task"
2019/03/07 13:09:15 [error] 10648#13864: *1316 upstream timed out (10060: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond) while connecting to upstream, client: 127.0.0.1, server: localhost, request: "GET /cdn/api/order/task/?pageindex=1&pagesize=10 HTTP/1.1", upstream: "http://127.0.0.1:5000/cdn/api/order/task/?pageindex=1&pagesize=10", host: "127.0.0.1", referrer: "http://127.0.0.1/cdn/static/task"
2019/03/07 13:13:47 [error] 10648#13864: *1318 upstream timed out (10060: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond) while connecting to upstream, client: 127.0.0.1, server: localhost, request: "GET /cdn/api/order/task/?pageindex=1&pagesize=10 HTTP/1.1", upstream: "http://127.0.0.1:5000/cdn/api/order/task/?pageindex=1&pagesize=10", host: "127.0.0.1", referrer: "http://127.0.0.1/cdn/static/task"
2019/03/07 13:18:24 [error] 10648#13864: *1320 upstream timed out (10060: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond) while connecting to upstream, client: 127.0.0.1, server: localhost, request: "GET /cdn/api/order/task/?pageindex=1&pagesize=10 HTTP/1.1", upstream: "http://127.0.0.1:5000/cdn/api/order/task/?pageindex=1&pagesize=10", host: "127.0.0.1", referrer: "http://127.0.0.1/cdn/static/task"
2019/03/07 13:23:06 [error] 10648#13864: *1322 upstream timed out (10060: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond) while connecting to upstream, client: 127.0.0.1, server: localhost, request: "GET /cdn/api/order/task/?pageindex=1&pagesize=10 HTTP/1.1", upstream: "http://127.0.0.1:5000/cdn/api/order/task/?pageindex=1&pagesize=10", host: "127.0.0.1", referrer: "http://127.0.0.1/cdn/static/task"
2019/03/07 13:27:52 [error] 10648#13864: *1324 upstream timed out (10060: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond) while connecting to upstream, client: 127.0.0.1, server: localhost, request: "GET /cdn/api/order/task/?pageindex=1&pagesize=10 HTTP/1.1", upstream: "http://127.0.0.1:5000/cdn/api/order/task/?pageindex=1&pagesize=10", host: "127.0.0.1", referrer: "http://127.0.0.1/cdn/static/task"
2019/03/07 13:37:40 [error] 10648#13864: *1328 upstream timed out (10060: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond) while connecting to upstream, client: 127.0.0.1, server: localhost, request: "GET /cdn/api/order/task/?pageindex=1&pagesize=10 HTTP/1.1", upstream: "http://127.0.0.1:5000/cdn/api/order/task/?pageindex=1&pagesize=10", host: "127.0.0.1", referrer: "http://127.0.0.1/cdn/static/task"
2019/03/07 13:42:42 [error] 10648#13864: *1330 upstream timed out (10060: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond) while connecting to upstream, client: 127.0.0.1, server: localhost, request: "GET /cdn/api/order/task/?pageindex=1&pagesize=10 HTTP/1.1", upstream: "http://127.0.0.1:5000/cdn/api/order/task/?pageindex=1&pagesize=10", host: "127.0.0.1", referrer: "http://127.0.0.1/cdn/static/task"
2019/03/07 13:53:00 [error] 10648#13864: *1334 upstream timed out (10060: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond) while connecting to upstream, client: 127.0.0.1, server: localhost, request: "GET /cdn/api/order/task/?pageindex=1&pagesize=10 HTTP/1.1", upstream: "http://127.0.0.1:5000/cdn/api/order/task/?pageindex=1&pagesize=10", host: "127.0.0.1", referrer: "http://127.0.0.1/cdn/static/task"
2019/03/07 13:58:16 [error] 10648#13864: *1336 upstream timed out (10060: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond) while connecting to upstream, client: 127.0.0.1, server: localhost, request: "GET /cdn/api/order/task/?pageindex=1&pagesize=10 HTTP/1.1", upstream: "http://127.0.0.1:5000/cdn/api/order/task/?pageindex=1&pagesize=10", host: "127.0.0.1", referrer: "http://127.0.0.1/cdn/static/task"
2019/03/07 14:03:38 [error] 10648#13864: *1338 upstream timed out (10060: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond) while connecting to upstream, client: 127.0.0.1, server: localhost, request: "GET /cdn/api/order/task/?pageindex=1&pagesize=10 HTTP/1.1", upstream: "http://127.0.0.1:5000/cdn/api/order/task/?pageindex=1&pagesize=10", host: "127.0.0.1", referrer: "http://127.0.0.1/cdn/static/task"
2019/03/07 14:09:05 [error] 10648#13864: *1340 upstream timed out (10060: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond) while connecting to upstream, client: 127.0.0.1, server: localhost, request: "GET /cdn/api/order/task/?pageindex=1&pagesize=10 HTTP/1.1", upstream: "http://127.0.0.1:5000/cdn/api/order/task/?pageindex=1&pagesize=10", host: "127.0.0.1", referrer: "http://127.0.0.1/cdn/static/task"
2019/03/07 14:14:37 [error] 10648#13864: *1342 upstream timed out (10060: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond) while connecting to upstream, client: 127.0.0.1, server: localhost, request: "GET /cdn/api/order/task/?pageindex=1&pagesize=10 HTTP/1.1", upstream: "http://127.0.0.1:5000/cdn/api/order/task/?pageindex=1&pagesize=10", host: "127.0.0.1", referrer: "http://127.0.0.1/cdn/static/task"
2019/03/07 15:26:09 [error] 10648#13864: *1391 upstream timed out (10060: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond) while connecting to upstream, client: 127.0.0.1, server: localhost, request: "GET /cdn/api/order/task/?pageindex=1&pagesize=10 HTTP/1.1", upstream: "http://127.0.0.1:5000/cdn/api/order/task/?pageindex=1&pagesize=10", host: "127.0.0.1", referrer: "http://127.0.0.1/cdn/static/task?token=bf0152240b4d16e269902b1c633fcc963183f462f19340f9c90823758db022ee&lang=cn"
2019/03/07 15:28:30 [error] 10648#13864: *1391 upstream timed out (10060: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond) while connecting to upstream, client: 127.0.0.1, server: localhost, request: "GET /cdn/api/order/task/?pageindex=1&pagesize=10 HTTP/1.1", upstream: "http://127.0.0.1:5000/cdn/api/order/task/?pageindex=1&pagesize=10", host: "127.0.0.1", referrer: "http://127.0.0.1/cdn/static/task?token=bf0152240b4d16e269902b1c633fcc963183f462f19340f9c90823758db022ee&lang=cn"
2019/03/07 15:35:47 [error] 10648#13864: *1447 upstream timed out (10060: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond) while connecting to upstream, client: 127.0.0.1, server: localhost, request: "GET /cdn/api/order/task/?pageindex=1&pagesize=10 HTTP/1.1", upstream: "http://127.0.0.1:5000/cdn/api/order/task/?pageindex=1&pagesize=10", host: "127.0.0.1", referrer: "http://127.0.0.1/cdn/static/task?token=bf0152240b4d16e269902b1c633fcc963183f462f19340f9c90823758db022ee&lang=cn"
2019/03/07 15:38:33 [error] 10648#13864: *1447 upstream timed out (10060: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond) while connecting to upstream, client: 127.0.0.1, server: localhost, request: "GET /cdn/api/order/task/?pageindex=1&pagesize=10 HTTP/1.1", upstream: "http://127.0.0.1:5000/cdn/api/order/task/?pageindex=1&pagesize=10", host: "127.0.0.1", referrer: "http://127.0.0.1/cdn/static/task?token=bf0152240b4d16e269902b1c633fcc963183f462f19340f9c90823758db022ee&lang=cn"
2019/03/07 15:41:24 [error] 10648#13864: *1447 upstream timed out (10060: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond) while connecting to upstream, client: 127.0.0.1, server: localhost, request: "GET /cdn/api/order/task/?pageindex=1&pagesize=10 HTTP/1.1", upstream: "http://127.0.0.1:5000/cdn/api/order/task/?pageindex=1&pagesize=10", host: "127.0.0.1", referrer: "http://127.0.0.1/cdn/static/task?token=bf0152240b4d16e269902b1c633fcc963183f462f19340f9c90823758db022ee&lang=cn"
2019/03/11 14:20:46 [error] 10648#13864: *2145 WSARecv() failed (10054: An existing connection was forcibly closed by the remote host) while reading response header from upstream, client: 127.0.0.1, server: localhost, request: "GET /cdn/opapi/order/task/?pageindex=1&pagesize=20 HTTP/1.1", upstream: "http://127.0.0.1:5001/cdn/opapi/order/task/?pageindex=1&pagesize=20", host: "127.0.0.1", referrer: "http://127.0.0.1/cdn/admin/create"
2019/03/11 14:21:29 [error] 10648#13864: *2148 WSARecv() failed (10054: An existing connection was forcibly closed by the remote host) while reading response header from upstream, client: 127.0.0.1, server: localhost, request: "GET /cdn/opapi/parameter/ HTTP/1.1", upstream: "http://127.0.0.1:5001/cdn/opapi/parameter/", host: "127.0.0.1", referrer: "http://127.0.0.1/cdn/admin/task"
2019/03/26 15:36:07 [error] 10352#24992: *857 upstream timed out (10060: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond) while connecting to upstream, client: 127.0.0.1, server: localhost, request: "POST /cdn/opapi/user/login/ HTTP/1.1", upstream: "http://127.0.0.1:5001/cdn/opapi/user/login/", host: "127.0.0.1", referrer: "http://127.0.0.1/cdn/admin/login"
2019/03/26 15:41:04 [error] 33072#14428: *5 upstream timed out (10060: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond) while connecting to upstream, client: 127.0.0.1, server: localhost, request: "GET /cdn/opapi/captcha/ HTTP/1.1", upstream: "http://127.0.0.1:5001/cdn/opapi/captcha/", host: "127.0.0.1", referrer: "http://127.0.0.1/cdn/admin/login"
2019/04/02 15:03:51 [error] 13644#14072: *814 upstream timed out (10060: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond) while connecting to upstream, client: 127.0.0.1, server: localhost, request: "GET /cdn/opapi/parameter/ HTTP/1.1", upstream: "http://127.0.0.1:5001/cdn/opapi/parameter/", host: "127.0.0.1", referrer: "http://127.0.0.1/cdn/admin/task/17294/update"
2019/04/04 18:07:35 [error] 13644#14072: *1567 upstream timed out (10060: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond) while connecting to upstream, client: 127.0.0.1, server: localhost, request: "GET /cdn/api/order/task/?pageindex=1&pagesize=10 HTTP/1.1", upstream: "http://127.0.0.1:5000/cdn/api/order/task/?pageindex=1&pagesize=10", host: "127.0.0.1", referrer: "http://127.0.0.1/cdn/static/task"
2019/04/08 15:11:08 [error] 11024#18288: *39 upstream timed out (10060: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond) while connecting to upstream, client: 127.0.0.1, server: localhost, request: "GET /cdn/api/order/task/?pageindex=1&pagesize=10 HTTP/1.1", upstream: "http://127.0.0.1:5000/cdn/api/order/task/?pageindex=1&pagesize=10", host: "127.0.0.1", referrer: "http://127.0.0.1/cdn/static/task"
2019/04/10 11:11:17 [error] 11024#18288: *6893 WSARecv() failed (10054: An existing connection was forcibly closed by the remote host) while reading response header from upstream, client: 127.0.0.1, server: localhost, request: "POST /cdn/opapi/prefetch HTTP/1.1", upstream: "http://127.0.0.1:5001/cdn/opapi/prefetch", host: "127.0.0.1", referrer: "http://127.0.0.1/cdn/admin/cache"
2019/04/10 11:11:29 [error] 11024#18288: *6893 WSARecv() failed (10054: An existing connection was forcibly closed by the remote host) while reading response header from upstream, client: 127.0.0.1, server: localhost, request: "POST /cdn/opapi/prefetch HTTP/1.1", upstream: "http://127.0.0.1:5001/cdn/opapi/prefetch", host: "127.0.0.1", referrer: "http://127.0.0.1/cdn/admin/cache"
2019/04/10 11:12:33 [error] 11024#18288: *6893 WSARecv() failed (10054: An existing connection was forcibly closed by the remote host) while reading response header from upstream, client: 127.0.0.1, server: localhost, request: "POST /cdn/opapi/prefetch HTTP/1.1", upstream: "http://127.0.0.1:5001/cdn/opapi/prefetch", host: "127.0.0.1", referrer: "http://127.0.0.1/cdn/admin/cache"
2019/04/10 11:14:43 [error] 11024#18288: *6900 WSARecv() failed (10054: An existing connection was forcibly closed by the remote host) while reading response header from upstream, client: 127.0.0.1, server: localhost, request: "POST /cdn/opapi/prefetch HTTP/1.1", upstream: "http://127.0.0.1:5001/cdn/opapi/prefetch", host: "127.0.0.1", referrer: "http://127.0.0.1/cdn/admin/cache"
2019/04/10 11:17:11 [error] 11024#18288: *6913 WSARecv() failed (10054: An existing connection was forcibly closed by the remote host) while reading response header from upstream, client: 127.0.0.1, server: localhost, request: "POST /cdn/opapi/prefetch HTTP/1.1", upstream: "http://127.0.0.1:5001/cdn/opapi/prefetch", host: "127.0.0.1", referrer: "http://127.0.0.1/cdn/admin/cache"
2019/04/10 11:22:46 [error] 11024#18288: *6943 WSARecv() failed (10054: An existing connection was forcibly closed by the remote host) while reading response header from upstream, client: 127.0.0.1, server: localhost, request: "POST /cdn/opapi/prefetch HTTP/1.1", upstream: "http://127.0.0.1:5001/cdn/opapi/prefetch", host: "127.0.0.1", referrer: "http://127.0.0.1/cdn/admin/cache"
2019/04/10 11:23:21 [error] 11024#18288: *6943 WSARecv() failed (10054: An existing connection was forcibly closed by the remote host) while reading response header from upstream, client: 127.0.0.1, server: localhost, request: "POST /cdn/opapi/prefetch HTTP/1.1", upstream: "http://127.0.0.1:5001/cdn/opapi/prefetch", host: "127.0.0.1", referrer: "http://127.0.0.1/cdn/admin/cache"
2019/04/10 11:25:33 [error] 11024#18288: *6943 WSARecv() failed (10054: An existing connection was forcibly closed by the remote host) while reading response header from upstream, client: 127.0.0.1, server: localhost, request: "POST /cdn/opapi/prefetch HTTP/1.1", upstream: "http://127.0.0.1:5001/cdn/opapi/prefetch", host: "127.0.0.1", referrer: "http://127.0.0.1/cdn/admin/cache"
2019/04/10 11:26:39 [error] 11024#18288: *6943 WSARecv() failed (10054: An existing connection was forcibly closed by the remote host) while reading response header from upstream, client: 127.0.0.1, server: localhost, request: "POST /cdn/opapi/prefetch HTTP/1.1", upstream: "http://127.0.0.1:5001/cdn/opapi/prefetch", host: "127.0.0.1", referrer: "http://127.0.0.1/cdn/admin/cache"
2019/04/10 11:27:23 [error] 11024#18288: *6943 WSARecv() failed (10054: An existing connection was forcibly closed by the remote host) while reading response header from upstream, client: 127.0.0.1, server: localhost, request: "POST /cdn/opapi/prefetch HTTP/1.1", upstream: "http://127.0.0.1:5001/cdn/opapi/prefetch", host: "127.0.0.1", referrer: "http://127.0.0.1/cdn/admin/cache"
2019/04/10 11:29:24 [error] 11024#18288: *6943 WSARecv() failed (10054: An existing connection was forcibly closed by the remote host) while reading response header from upstream, client: 127.0.0.1, server: localhost, request: "POST /cdn/opapi/prefetch HTTP/1.1", upstream: "http://127.0.0.1:5001/cdn/opapi/prefetch", host: "127.0.0.1", referrer: "http://127.0.0.1/cdn/admin/cache"
2019/04/10 11:30:03 [error] 11024#18288: *6943 WSARecv() failed (10054: An existing connection was forcibly closed by the remote host) while reading response header from upstream, client: 127.0.0.1, server: localhost, request: "POST /cdn/opapi/prefetch HTTP/1.1", upstream: "http://127.0.0.1:5001/cdn/opapi/prefetch", host: "127.0.0.1", referrer: "http://127.0.0.1/cdn/admin/cache"
2019/04/10 11:30:40 [error] 11024#18288: *6943 WSARecv() failed (10054: An existing connection was forcibly closed by the remote host) while reading response header from upstream, client: 127.0.0.1, server: localhost, request: "POST /cdn/opapi/prefetch HTTP/1.1", upstream: "http://127.0.0.1:5001/cdn/opapi/prefetch", host: "127.0.0.1", referrer: "http://127.0.0.1/cdn/admin/cache"
2019/04/10 11:31:05 [error] 11024#18288: *6943 WSARecv() failed (10054: An existing connection was forcibly closed by the remote host) while reading response header from upstream, client: 127.0.0.1, server: localhost, request: "POST /cdn/opapi/prefetch HTTP/1.1", upstream: "http://127.0.0.1:5001/cdn/opapi/prefetch", host: "127.0.0.1", referrer: "http://127.0.0.1/cdn/admin/cache"
2019/04/10 11:31:22 [error] 11024#18288: *6943 WSARecv() failed (10054: An existing connection was forcibly closed by the remote host) while reading response header from upstream, client: 127.0.0.1, server: localhost, request: "POST /cdn/opapi/prefetch HTTP/1.1", upstream: "http://127.0.0.1:5001/cdn/opapi/prefetch", host: "127.0.0.1", referrer: "http://127.0.0.1/cdn/admin/cache"
2019/04/10 11:32:17 [error] 11024#18288: *6943 WSARecv() failed (10054: An existing connection was forcibly closed by the remote host) while reading response header from upstream, client: 127.0.0.1, server: localhost, request: "POST /cdn/opapi/prefetch HTTP/1.1", upstream: "http://127.0.0.1:5001/cdn/opapi/prefetch", host: "127.0.0.1", referrer: "http://127.0.0.1/cdn/admin/cache"
2019/04/10 11:33:31 [error] 11024#18288: *6943 WSARecv() failed (10054: An existing connection was forcibly closed by the remote host) while reading response header from upstream, client: 127.0.0.1, server: localhost, request: "POST /cdn/opapi/prefetch HTTP/1.1", upstream: "http://127.0.0.1:5001/cdn/opapi/prefetch", host: "127.0.0.1", referrer: "http://127.0.0.1/cdn/admin/cache"
2019/04/10 11:35:17 [error] 11024#18288: *6943 WSARecv() failed (10054: An existing connection was forcibly closed by the remote host) while reading response header from upstream, client: 127.0.0.1, server: localhost, request: "POST /cdn/opapi/prefetch HTTP/1.1", upstream: "http://127.0.0.1:5001/cdn/opapi/prefetch", host: "127.0.0.1", referrer: "http://127.0.0.1/cdn/admin/cache"
2019/04/10 11:35:40 [error] 11024#18288: *6943 WSARecv() failed (10054: An existing connection was forcibly closed by the remote host) while reading response header from upstream, client: 127.0.0.1, server: localhost, request: "POST /cdn/opapi/prefetch HTTP/1.1", upstream: "http://127.0.0.1:5001/cdn/opapi/prefetch", host: "127.0.0.1", referrer: "http://127.0.0.1/cdn/admin/cache"
2019/04/10 11:38:29 [error] 11024#18288: *6943 WSARecv() failed (10054: An existing connection was forcibly closed by the remote host) while reading response header from upstream, client: 127.0.0.1, server: localhost, request: "POST /cdn/opapi/prefetch HTTP/1.1", upstream: "http://127.0.0.1:5001/cdn/opapi/prefetch", host: "127.0.0.1", referrer: "http://127.0.0.1/cdn/admin/cache"
2019/04/15 15:29:10 [error] 948#5104: *88 WSARecv() failed (10054: An existing connection was forcibly closed by the remote host) while reading response header from upstream, client: 127.0.0.1, server: localhost, request: "GET /cdn/opapi/parameter/ HTTP/1.1", upstream: "http://127.0.0.1:5001/cdn/opapi/parameter/", host: "127.0.0.1", referrer: "http://127.0.0.1/cdn/admin/"
2019/04/25 16:44:21 [error] 16708#2836: *1 CreateFile() "E:\nginx-1.9.1/html/favicon.ico" failed (2: The system cannot find the file specified), client: 127.0.0.1, server: localhost, request: "GET /favicon.ico HTTP/1.1", host: "127.0.0.1:8888", referrer: "http://127.0.0.1:8888/"
2019/04/25 17:25:16 [error] 16708#2836: *3 CreateFile() "E:\nginx-1.9.1/html/favicon.ico" failed (2: The system cannot find the file specified), client: 127.0.0.1, server: localhost, request: "GET /favicon.ico HTTP/1.1", host: "127.0.0.1:8888", referrer: "http://127.0.0.1:8888/"
2019/04/25 17:25:56 [error] 16708#2836: *3 CreateFile() "E:/data/git/node/kvm/dev/bms_vnc/vnc//index.html" failed (3: The system cannot find the path specified), client: 127.0.0.1, server: localhost, request: "GET /vnc/index.html HTTP/1.1", host: "127.0.0.1:8888"
2019/04/25 17:27:09 [error] 16708#2836: *3 CreateFile() "E:/data/git/node/kvm/dev/bms_vnc/vnc//index.html" failed (3: The system cannot find the path specified), client: 127.0.0.1, server: localhost, request: "GET /vnc/index.html HTTP/1.1", host: "127.0.0.1:8888"
2019/04/25 17:27:10 [error] 16708#2836: *3 CreateFile() "E:/data/git/node/kvm/dev/bms_vnc/vnc//index.html" failed (3: The system cannot find the path specified), client: 127.0.0.1, server: localhost, request: "GET /vnc/index.html HTTP/1.1", host: "127.0.0.1:8888"
2019/04/25 17:27:10 [error] 16708#2836: *3 CreateFile() "E:/data/git/node/kvm/dev/bms_vnc/vnc//index.html" failed (3: The system cannot find the path specified), client: 127.0.0.1, server: localhost, request: "GET /vnc/index.html HTTP/1.1", host: "127.0.0.1:8888"
2019/04/25 17:27:10 [error] 16708#2836: *3 CreateFile() "E:/data/git/node/kvm/dev/bms_vnc/vnc//index.html" failed (3: The system cannot find the path specified), client: 127.0.0.1, server: localhost, request: "GET /vnc/index.html HTTP/1.1", host: "127.0.0.1:8888"
2019/04/25 17:27:10 [error] 16708#2836: *3 CreateFile() "E:/data/git/node/kvm/dev/bms_vnc/vnc//index.html" failed (3: The system cannot find the path specified), client: 127.0.0.1, server: localhost, request: "GET /vnc/index.html HTTP/1.1", host: "127.0.0.1:8888"
2019/04/25 17:27:11 [error] 16708#2836: *3 CreateFile() "E:/data/git/node/kvm/dev/bms_vnc/vnc//index.html" failed (3: The system cannot find the path specified), client: 127.0.0.1, server: localhost, request: "GET /vnc/index.html HTTP/1.1", host: "127.0.0.1:8888"
2019/04/25 17:27:11 [error] 16708#2836: *3 CreateFile() "E:/data/git/node/kvm/dev/bms_vnc/vnc//index.html" failed (3: The system cannot find the path specified), client: 127.0.0.1, server: localhost, request: "GET /vnc/index.html HTTP/1.1", host: "127.0.0.1:8888"
2019/04/25 17:27:11 [error] 16708#2836: *3 CreateFile() "E:/data/git/node/kvm/dev/bms_vnc/vnc//index.html" failed (3: The system cannot find the path specified), client: 127.0.0.1, server: localhost, request: "GET /vnc/index.html HTTP/1.1", host: "127.0.0.1:8888"
2019/04/25 17:29:32 [error] 16708#2836: *7 CreateFile() "E:/data/git/node/kvm/dev/bms_vnc/vnc//index.html" failed (3: The system cannot find the path specified), client: 127.0.0.1, server: localhost, request: "GET /vnc/index.html HTTP/1.1", host: "127.0.0.1:8888"
2019/04/25 17:29:43 [error] 16708#2836: *7 CreateFile() "E:/data/git/node/kvm/dev/bms_vnc/vnc//vnc_lite.html" failed (3: The system cannot find the path specified), client: 127.0.0.1, server: localhost, request: "GET /vnc/vnc_lite.html HTTP/1.1", host: "127.0.0.1:8888"
2019/04/25 17:31:00 [error] 16708#2836: *7 CreateFile() "E:/data/git/node/kvm/dev/bms_vnc/vnc//vnc_lite.html" failed (3: The system cannot find the path specified), client: 127.0.0.1, server: localhost, request: "GET /vnc/vnc_lite.html HTTP/1.1", host: "127.0.0.1:8888"
2019/04/25 17:31:01 [error] 16708#2836: *7 CreateFile() "E:/data/git/node/kvm/dev/bms_vnc/vnc//vnc_lite.html" failed (3: The system cannot find the path specified), client: 127.0.0.1, server: localhost, request: "GET /vnc/vnc_lite.html HTTP/1.1", host: "127.0.0.1:8888"
2019/04/25 17:31:01 [error] 16708#2836: *7 CreateFile() "E:/data/git/node/kvm/dev/bms_vnc/vnc//vnc_lite.html" failed (3: The system cannot find the path specified), client: 127.0.0.1, server: localhost, request: "GET /vnc/vnc_lite.html HTTP/1.1", host: "127.0.0.1:8888"
2019/04/25 17:31:10 [error] 16708#2836: *7 CreateFile() "E:/data/git/node/kvm/dev/bms_vnc/vnc//index.html" failed (3: The system cannot find the path specified), client: 127.0.0.1, server: localhost, request: "GET /vnc/index.html HTTP/1.1", host: "127.0.0.1:8888"
2019/04/25 17:31:26 [error] 16708#2836: *7 CreateFile() "E:/data/git/node/kvm/dev/bms_vnc/vnc//index.html" failed (3: The system cannot find the path specified), client: 127.0.0.1, server: localhost, request: "GET /vnc/index.html HTTP/1.1", host: "127.0.0.1:8888"
2019/04/25 17:31:27 [error] 16708#2836: *7 CreateFile() "E:/data/git/node/kvm/dev/bms_vnc/vnc//index.html" failed (3: The system cannot find the path specified), client: 127.0.0.1, server: localhost, request: "GET /vnc/index.html HTTP/1.1", host: "127.0.0.1:8888"
2019/04/25 17:31:27 [error] 16708#2836: *7 CreateFile() "E:/data/git/node/kvm/dev/bms_vnc/vnc//index.html" failed (3: The system cannot find the path specified), client: 127.0.0.1, server: localhost, request: "GET /vnc/index.html HTTP/1.1", host: "127.0.0.1:8888"
2019/04/25 17:32:41 [error] 16708#2836: *7 CreateFile() "E:/data/git/node/kvm/dev/bms_vnc/vnc//index.html" failed (3: The system cannot find the path specified), client: 127.0.0.1, server: localhost, request: "GET /vnc/index.html HTTP/1.1", host: "127.0.0.1:8888"
2019/04/25 17:32:42 [error] 16708#2836: *7 CreateFile() "E:/data/git/node/kvm/dev/bms_vnc/vnc//index.html" failed (3: The system cannot find the path specified), client: 127.0.0.1, server: localhost, request: "GET /vnc/index.html HTTP/1.1", host: "127.0.0.1:8888"
2019/04/25 17:32:42 [error] 16708#2836: *7 CreateFile() "E:/data/git/node/kvm/dev/bms_vnc/vnc//index.html" failed (3: The system cannot find the path specified), client: 127.0.0.1, server: localhost, request: "GET /vnc/index.html HTTP/1.1", host: "127.0.0.1:8888"
2019/04/25 17:32:42 [error] 16708#2836: *7 CreateFile() "E:/data/git/node/kvm/dev/bms_vnc/vnc//index.html" failed (3: The system cannot find the path specified), client: 127.0.0.1, server: localhost, request: "GET /vnc/index.html HTTP/1.1", host: "127.0.0.1:8888"
2019/04/25 17:32:42 [error] 16708#2836: *7 CreateFile() "E:/data/git/node/kvm/dev/bms_vnc/vnc//index.html" failed (3: The system cannot find the path specified), client: 127.0.0.1, server: localhost, request: "GET /vnc/index.html HTTP/1.1", host: "127.0.0.1:8888"
2019/04/25 17:35:42 [error] 16708#2836: *13 CreateFile() "E:/data/git/node/kvm/dev/bms_vnc/vnc//index.html" failed (3: The system cannot find the path specified), client: 127.0.0.1, server: localhost, request: "GET /vnc/index.html HTTP/1.1", host: "127.0.0.1:8888"
2019/04/25 17:35:43 [error] 16708#2836: *13 CreateFile() "E:/data/git/node/kvm/dev/bms_vnc/vnc//index.html" failed (3: The system cannot find the path specified), client: 127.0.0.1, server: localhost, request: "GET /vnc/index.html HTTP/1.1", host: "127.0.0.1:8888"
2019/04/25 17:35:43 [error] 16708#2836: *13 CreateFile() "E:/data/git/node/kvm/dev/bms_vnc/vnc//index.html" failed (3: The system cannot find the path specified), client: 127.0.0.1, server: localhost, request: "GET /vnc/index.html HTTP/1.1", host: "127.0.0.1:8888"
2019/04/25 17:35:43 [error] 16708#2836: *13 CreateFile() "E:/data/git/node/kvm/dev/bms_vnc/vnc//index.html" failed (3: The system cannot find the path specified), client: 127.0.0.1, server: localhost, request: "GET /vnc/index.html HTTP/1.1", host: "127.0.0.1:8888"
2019/04/25 17:39:52 [error] 16708#2836: *16 CreateFile() "E:/data/git/node/kvm/dev/bms_vnc/vnc//index.html" failed (3: The system cannot find the path specified), client: 127.0.0.1, server: localhost, request: "GET /vnc/index.html HTTP/1.1", host: "127.0.0.1:8888"
2019/04/25 17:40:00 [error] 16708#2836: *16 "E:/data/git/node/kvm/dev/bms_vnc/vnc//index.html" is not found (3: The system cannot find the path specified), client: 127.0.0.1, server: localhost, request: "GET /vnc/ HTTP/1.1", host: "127.0.0.1:8888"
2019/04/25 17:40:31 [error] 16708#2836: *16 "E:/data/git/node/kvm/dev/bms_vnc/vnc//index.html" is not found (3: The system cannot find the path specified), client: 127.0.0.1, server: localhost, request: "GET /vnc/ HTTP/1.1", host: "127.0.0.1:8888"
2019/04/25 17:40:32 [error] 16708#2836: *16 "E:/data/git/node/kvm/dev/bms_vnc/vnc//index.html" is not found (3: The system cannot find the path specified), client: 127.0.0.1, server: localhost, request: "GET /vnc/ HTTP/1.1", host: "127.0.0.1:8888"
2019/04/25 17:40:32 [error] 16708#2836: *16 "E:/data/git/node/kvm/dev/bms_vnc/vnc//index.html" is not found (3: The system cannot find the path specified), client: 127.0.0.1, server: localhost, request: "GET /vnc/ HTTP/1.1", host: "127.0.0.1:8888"
2019/04/25 17:40:32 [error] 16708#2836: *16 "E:/data/git/node/kvm/dev/bms_vnc/vnc//index.html" is not found (3: The system cannot find the path specified), client: 127.0.0.1, server: localhost, request: "GET /vnc/ HTTP/1.1", host: "127.0.0.1:8888"
2019/04/25 17:40:32 [error] 16708#2836: *16 "E:/data/git/node/kvm/dev/bms_vnc/vnc//index.html" is not found (3: The system cannot find the path specified), client: 127.0.0.1, server: localhost, request: "GET /vnc/ HTTP/1.1", host: "127.0.0.1:8888"
2019/04/25 17:40:32 [error] 16708#2836: *16 "E:/data/git/node/kvm/dev/bms_vnc/vnc//index.html" is not found (3: The system cannot find the path specified), client: 127.0.0.1, server: localhost, request: "GET /vnc/ HTTP/1.1", host: "127.0.0.1:8888"
2019/04/25 17:40:55 [error] 16708#2836: *16 "E:/data/git/node/kvm/dev/bms_vnc/vnc//index.html" is not found (3: The system cannot find the path specified), client: 127.0.0.1, server: localhost, request: "GET /vnc/ HTTP/1.1", host: "127.0.0.1:8888"
2019/04/25 17:40:55 [error] 16708#2836: *16 "E:/data/git/node/kvm/dev/bms_vnc/vnc//index.html" is not found (3: The system cannot find the path specified), client: 127.0.0.1, server: localhost, request: "GET /vnc/ HTTP/1.1", host: "127.0.0.1:8888"
2019/04/25 17:40:56 [error] 16708#2836: *16 "E:/data/git/node/kvm/dev/bms_vnc/vnc//index.html" is not found (3: The system cannot find the path specified), client: 127.0.0.1, server: localhost, request: "GET /vnc/ HTTP/1.1", host: "127.0.0.1:8888"
2019/04/25 17:40:58 [error] 16708#2836: *16 "E:/data/git/node/kvm/dev/bms_vnc/vnc//index.html" is not found (3: The system cannot find the path specified), client: 127.0.0.1, server: localhost, request: "GET /vnc/ HTTP/1.1", host: "127.0.0.1:8888"
2019/04/25 17:40:58 [error] 16708#2836: *16 "E:/data/git/node/kvm/dev/bms_vnc/vnc//index.html" is not found (3: The system cannot find the path specified), client: 127.0.0.1, server: localhost, request: "GET /vnc/ HTTP/1.1", host: "127.0.0.1:8888"
2019/04/25 17:40:59 [error] 16708#2836: *16 "E:/data/git/node/kvm/dev/bms_vnc/vnc//index.html" is not found (3: The system cannot find the path specified), client: 127.0.0.1, server: localhost, request: "GET /vnc/ HTTP/1.1", host: "127.0.0.1:8888"
2019/04/25 17:40:59 [error] 16708#2836: *16 "E:/data/git/node/kvm/dev/bms_vnc/vnc//index.html" is not found (3: The system cannot find the path specified), client: 127.0.0.1, server: localhost, request: "GET /vnc/ HTTP/1.1", host: "127.0.0.1:8888"
2019/04/25 17:40:59 [error] 16708#2836: *16 "E:/data/git/node/kvm/dev/bms_vnc/vnc//index.html" is not found (3: The system cannot find the path specified), client: 127.0.0.1, server: localhost, request: "GET /vnc/ HTTP/1.1", host: "127.0.0.1:8888"
2019/04/25 17:40:59 [error] 16708#2836: *16 "E:/data/git/node/kvm/dev/bms_vnc/vnc//index.html" is not found (3: The system cannot find the path specified), client: 127.0.0.1, server: localhost, request: "GET /vnc/ HTTP/1.1", host: "127.0.0.1:8888"
2019/04/25 17:41:11 [error] 16708#2836: *16 "E:/data/git/node/kvm/dev/bms_vnc/vnc//index.html" is not found (3: The system cannot find the path specified), client: 127.0.0.1, server: localhost, request: "GET /vnc/ HTTP/1.1", host: "127.0.0.1:8888"
2019/04/25 17:41:12 [error] 16708#2836: *16 "E:/data/git/node/kvm/dev/bms_vnc/vnc//index.html" is not found (3: The system cannot find the path specified), client: 127.0.0.1, server: localhost, request: "GET /vnc/ HTTP/1.1", host: "127.0.0.1:8888"
2019/04/25 17:41:21 [error] 16708#2836: *16 "E:/data/git/node/kvm/dev/bms_vnc/vnc//index.html" is not found (3: The system cannot find the path specified), client: 127.0.0.1, server: localhost, request: "GET /vnc/ HTTP/1.1", host: "127.0.0.1:8888"
2019/04/25 17:41:25 [error] 16708#2836: *16 "E:/data/git/node/kvm/dev/bms_vnc/vnc//index.html" is not found (3: The system cannot find the path specified), client: 127.0.0.1, server: localhost, request: "GET /vnc/ HTTP/1.1", host: "127.0.0.1:8888"
2019/04/25 17:41:25 [error] 16708#2836: *16 "E:/data/git/node/kvm/dev/bms_vnc/vnc//index.html" is not found (3: The system cannot find the path specified), client: 127.0.0.1, server: localhost, request: "GET /vnc/ HTTP/1.1", host: "127.0.0.1:8888"
2019/04/25 17:41:26 [error] 16708#2836: *16 "E:/data/git/node/kvm/dev/bms_vnc/vnc//index.html" is not found (3: The system cannot find the path specified), client: 127.0.0.1, server: localhost, request: "GET /vnc/ HTTP/1.1", host: "127.0.0.1:8888"
2019/04/25 17:43:24 [emerg] 12504#20552: invalid number of arguments in "root" directive in E:\nginx-1.9.1/conf/nginx.conf:53
2019/04/25 17:43:34 [emerg] 2712#18864: invalid number of arguments in "root" directive in E:\nginx-1.9.1/conf/nginx.conf:53
2019/04/25 17:43:47 [error] 16708#2836: *23 CreateFile() "E:/data/git/node/kvm/dev/bms_vnc/vnc/" failed (3: The system cannot find the path specified), client: 127.0.0.1, server: localhost, request: "GET /vnc HTTP/1.1", host: "127.0.0.1:8888"
2019/04/25 17:44:01 [error] 16708#2836: *23 CreateFile() "E:/data/git/node/kvm/dev/bms_vnc/vnc//index" failed (3: The system cannot find the path specified), client: 127.0.0.1, server: localhost, request: "GET /vnc/index HTTP/1.1", host: "127.0.0.1:8888"
2019/04/25 17:44:49 [emerg] 19652#14924: invalid number of arguments in "root" directive in E:\nginx-1.9.1/conf/nginx.conf:53
2019/04/25 17:44:49 [alert] 21068#21064: worker process 19652 exited with code 1
2019/04/25 17:44:49 [alert] 21068#21064: could not respawn worker
2019/04/25 17:45:02 [emerg] 20632#20892: invalid number of arguments in "root" directive in E:\nginx-1.9.1/conf/nginx.conf:53
2019/04/25 17:45:02 [alert] 17772#3612: worker process 20632 exited with code 1
2019/04/25 17:45:02 [alert] 17772#3612: could not respawn worker
2019/04/25 17:45:44 [emerg] 20140#13784: invalid number of arguments in "root" directive in E:\nginx-1.9.1/conf/nginx.conf:53
2019/04/25 17:45:44 [alert] 16648#6508: worker process 20140 exited with code 1
2019/04/25 17:45:44 [alert] 16648#6508: could not respawn worker
2019/04/25 17:46:56 [emerg] 18172#20220: invalid number of arguments in "root" directive in E:\nginx-1.9.1/conf/nginx.conf:53
2019/04/25 17:48:47 [emerg] 18920#17780: invalid number of arguments in "root" directive in E:\nginx-1.9.1/conf/nginx.conf:53
2019/04/25 17:49:52 [emerg] 12980#20372: invalid number of arguments in "root" directive in E:\nginx-1.9.1/conf/nginx.conf:53
2019/04/25 17:50:12 [emerg] 4112#5660: invalid number of arguments in "root" directive in E:\nginx-1.9.1/conf/nginx.conf:53
2019/04/25 17:51:19 [notice] 12124#20212: signal process started
2019/04/25 17:51:19 [error] 12124#20212: OpenEvent("Global\ngx_stop_21068") failed (2: The system cannot find the file specified)
2019/04/25 17:52:01 [error] 16708#2836: *26 CreateFile() "E:/data/git/node/kvm/dev/bms_vnc/vnc/" failed (3: The system cannot find the path specified), client: 127.0.0.1, server: localhost, request: "GET /vnc HTTP/1.1", host: "127.0.0.1:8888"
2019/04/25 17:53:23 [error] 16708#2836: *26 CreateFile() "E:/data/git/node/kvm/dev/bms_vnc/vnc/" failed (3: The system cannot find the path specified), client: 127.0.0.1, server: localhost, request: "GET /vnc HTTP/1.1", host: "127.0.0.1:8888"
2019/04/25 17:54:31 [error] 16708#2836: *26 CreateFile() "E:/data/git/node/kvm/dev/bms_vnc/vnc/" failed (3: The system cannot find the path specified), client: 127.0.0.1, server: localhost, request: "GET /vnc HTTP/1.1", host: "127.0.0.1:8888"
2019/04/25 17:54:32 [error] 16708#2836: *26 CreateFile() "E:/data/git/node/kvm/dev/bms_vnc/vnc/" failed (3: The system cannot find the path specified), client: 127.0.0.1, server: localhost, request: "GET /vnc HTTP/1.1", host: "127.0.0.1:8888"
2019/04/25 17:54:32 [error] 16708#2836: *26 CreateFile() "E:/data/git/node/kvm/dev/bms_vnc/vnc/" failed (3: The system cannot find the path specified), client: 127.0.0.1, server: localhost, request: "GET /vnc HTTP/1.1", host: "127.0.0.1:8888"
2019/04/25 17:54:32 [error] 16708#2836: *26 CreateFile() "E:/data/git/node/kvm/dev/bms_vnc/vnc/" failed (3: The system cannot find the path specified), client: 127.0.0.1, server: localhost, request: "GET /vnc HTTP/1.1", host: "127.0.0.1:8888"
2019/04/25 17:54:32 [error] 16708#2836: *26 CreateFile() "E:/data/git/node/kvm/dev/bms_vnc/vnc/" failed (3: The system cannot find the path specified), client: 127.0.0.1, server: localhost, request: "GET /vnc HTTP/1.1", host: "127.0.0.1:8888"
2019/04/25 17:54:32 [error] 16708#2836: *26 CreateFile() "E:/data/git/node/kvm/dev/bms_vnc/vnc/" failed (3: The system cannot find the path specified), client: 127.0.0.1, server: localhost, request: "GET /vnc HTTP/1.1", host: "127.0.0.1:8888"
2019/04/25 17:54:33 [error] 16708#2836: *26 CreateFile() "E:/data/git/node/kvm/dev/bms_vnc/vnc/" failed (3: The system cannot find the path specified), client: 127.0.0.1, server: localhost, request: "GET /vnc HTTP/1.1", host: "127.0.0.1:8888"
2019/04/25 17:54:33 [error] 16708#2836: *26 CreateFile() "E:/data/git/node/kvm/dev/bms_vnc/vnc/" failed (3: The system cannot find the path specified), client: 127.0.0.1, server: localhost, request: "GET /vnc HTTP/1.1", host: "127.0.0.1:8888"
2019/04/25 17:56:53 [alert] 18444#14480: worker process 21668 exited with code C0000142
2019/04/25 17:56:53 [alert] 18444#14480: could not respawn worker
2019/04/25 17:56:53 [alert] 19324#17488: the event "ngx_master_19324" was not signaled for 5s
2019/04/25 17:56:53 [alert] 19324#17488: could not respawn worker
2019/04/25 18:03:00 [error] 9196#10628: *2 CreateFile() "E:/workspace/bms_vnc/vnc/favicon.ico" failed (2: The system cannot find the file specified), client: 127.0.0.1, server: localhost, request: "GET /favicon.ico HTTP/1.1", host: "127.0.0.1:8888", referrer: "http://127.0.0.1:8888/vnc"
2019/04/25 18:03:21 [error] 9196#10628: *4 CreateFile() "E:/workspace/bms_vnc/vnc/index.hmtl" failed (2: The system cannot find the file specified), client: 127.0.0.1, server: localhost, request: "GET /vnc/index.hmtl HTTP/1.1", host: "127.0.0.1:8888"
2019/04/25 18:03:37 [error] 9196#10628: *4 CreateFile() "E:/workspace/bms_vnc/vnc/lib/bootstrap.min.css.map" failed (2: The system cannot find the file specified), client: 127.0.0.1, server: localhost, request: "GET /vnc/lib/bootstrap.min.css.map HTTP/1.1", host: "127.0.0.1:8888"
2019/04/25 18:03:41 [error] 9196#10628: *4 CreateFile() "E:/workspace/bms_vnc/vnc/lib/bootstrap.min.css.map" failed (2: The system cannot find the file specified), client: 127.0.0.1, server: localhost, request: "GET /vnc/lib/bootstrap.min.css.map HTTP/1.1", host: "127.0.0.1:8888"
2019/04/25 18:03:43 [error] 9196#10628: *4 CreateFile() "E:/workspace/bms_vnc/vnc/lib/bootstrap.min.css.map" failed (2: The system cannot find the file specified), client: 127.0.0.1, server: localhost, request: "GET /vnc/lib/bootstrap.min.css.map HTTP/1.1", host: "127.0.0.1:8888"
2019/04/25 18:06:36 [error] 9196#10628: *7 CreateFile() "E:/workspace/bms_vnc/vnc/lib/bootstrap.min.css.map" failed (2: The system cannot find the file specified), client: 127.0.0.1, server: localhost, request: "GET /vnc/lib/bootstrap.min.css.map HTTP/1.1", host: "127.0.0.1:8888"
2019/04/25 18:09:08 [error] 9196#10628: *22 upstream timed out (10060: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond) while connecting to upstream, client: 127.0.0.1, server: localhost, request: "GET /websockify/?authId=6842026a1f2d4707996fb355cea81c30&token=c2cce78b9503c7883e286b2f588d1f8ee5b06f94e2cd5f28d9e398821cf13e04 HTTP/1.1", upstream: "http://127.0.0.1:3001/websockify/?authId=6842026a1f2d4707996fb355cea81c30&token=c2cce78b9503c7883e286b2f588d1f8ee5b06f94e2cd5f28d9e398821cf13e04", host: "127.0.0.1:8888"
2019/04/25 18:15:04 [emerg] 12492#2508: "proxy_http_version" directive is duplicate in E:\nginx-1.9.1/conf/nginx.conf:77
2019/04/25 18:15:55 [emerg] 12752#13188: "proxy_http_version" directive is duplicate in E:\nginx-1.9.1/conf/nginx.conf:77
2019/04/25 18:28:48 [error] 868#12064: *18 WSARecv() failed (10054: An existing connection was forcibly closed by the remote host) while proxying upgraded connection, client: 127.0.0.1, server: localhost, request: "GET /websockify/?authId=6842026a1f2d4707996fb355cea81c30&token=c2cce78b9503c7883e286b2f588d1f8ee5b06f94e2cd5f28d9e398821cf13e04 HTTP/1.1", upstream: "http://127.0.0.1:3001/websockify/?authId=6842026a1f2d4707996fb355cea81c30&token=c2cce78b9503c7883e286b2f588d1f8ee5b06f94e2cd5f28d9e398821cf13e04", host: "127.0.0.1:8888"
2019/04/25 18:29:33 [error] 868#12064: *21 WSARecv() failed (10054: An existing connection was forcibly closed by the remote host) while proxying upgraded connection, client: 127.0.0.1, server: localhost, request: "GET /websockify/?authId=6842026a1f2d4707996fb355cea81c30&token=c2cce78b9503c7883e286b2f588d1f8ee5b06f94e2cd5f28d9e398821cf13e04 HTTP/1.1", upstream: "http://127.0.0.1:3001/websockify/?authId=6842026a1f2d4707996fb355cea81c30&token=c2cce78b9503c7883e286b2f588d1f8ee5b06f94e2cd5f28d9e398821cf13e04", host: "127.0.0.1:8888"
2019/04/25 18:30:05 [error] 868#12064: *24 WSARecv() failed (10054: An existing connection was forcibly closed by the remote host) while proxying upgraded connection, client: 127.0.0.1, server: localhost, request: "GET /websockify/?authId=6842026a1f2d4707996fb355cea81c30&token=c2cce78b9503c7883e286b2f588d1f8ee5b06f94e2cd5f28d9e398821cf13e04 HTTP/1.1", upstream: "http://127.0.0.1:3001/websockify/?authId=6842026a1f2d4707996fb355cea81c30&token=c2cce78b9503c7883e286b2f588d1f8ee5b06f94e2cd5f28d9e398821cf13e04", host: "127.0.0.1:8888"
2019/04/25 18:31:00 [error] 868#12064: *27 WSARecv() failed (10054: An existing connection was forcibly closed by the remote host) while proxying upgraded connection, client: 127.0.0.1, server: localhost, request: "GET /websockify/?authId=6842026a1f2d4707996fb355cea81c30&token=c2cce78b9503c7883e286b2f588d1f8ee5b06f94e2cd5f28d9e398821cf13e04 HTTP/1.1", upstream: "http://127.0.0.1:3001/websockify/?authId=6842026a1f2d4707996fb355cea81c30&token=c2cce78b9503c7883e286b2f588d1f8ee5b06f94e2cd5f28d9e398821cf13e04", host: "127.0.0.1:8888"
2019/04/25 18:32:47 [error] 868#12064: *30 WSARecv() failed (10054: An existing connection was forcibly closed by the remote host) while proxying upgraded connection, client: 127.0.0.1, server: localhost, request: "GET /websockify/?authId=6842026a1f2d4707996fb355cea81c30&token=c2cce78b9503c7883e286b2f588d1f8ee5b06f94e2cd5f28d9e398821cf13e04 HTTP/1.1", upstream: "http://127.0.0.1:3001/websockify/?authId=6842026a1f2d4707996fb355cea81c30&token=c2cce78b9503c7883e286b2f588d1f8ee5b06f94e2cd5f28d9e398821cf13e04", host: "127.0.0.1:8888"
2019/04/25 18:33:45 [error] 868#12064: *33 WSARecv() failed (10054: An existing connection was forcibly closed by the remote host) while proxying upgraded connection, client: 127.0.0.1, server: localhost, request: "GET /websockify/?authId=6842026a1f2d4707996fb355cea81c30&token=c2cce78b9503c7883e286b2f588d1f8ee5b06f94e2cd5f28d9e398821cf13e04 HTTP/1.1", upstream: "http://127.0.0.1:3001/websockify/?authId=6842026a1f2d4707996fb355cea81c30&token=c2cce78b9503c7883e286b2f588d1f8ee5b06f94e2cd5f28d9e398821cf13e04", host: "127.0.0.1:8888"
2019/04/25 18:36:04 [error] 868#12064: *39 WSARecv() failed (10054: An existing connection was forcibly closed by the remote host) while proxying upgraded connection, client: 127.0.0.1, server: localhost, request: "GET /websockify/?authId=6842026a1f2d4707996fb355cea81c30&token=c2cce78b9503c7883e286b2f588d1f8ee5b06f94e2cd5f28d9e398821cf13e04 HTTP/1.1", upstream: "http://127.0.0.1:3001/websockify/?authId=6842026a1f2d4707996fb355cea81c30&token=c2cce78b9503c7883e286b2f588d1f8ee5b06f94e2cd5f28d9e398821cf13e04", host: "127.0.0.1:8888"
2019/04/25 18:40:01 [error] 868#12064: *52 WSARecv() failed (10054: An existing connection was forcibly closed by the remote host) while proxying upgraded connection, client: 127.0.0.1, server: localhost, request: "GET /websockify/?authId=6842026a1f2d4707996fb355cea81c30&token=c3d0e26091ad31385db067c439f708dfebe6474edbfebd9338108033e9ab3b26 HTTP/1.1", upstream: "http://127.0.0.1:3001/websockify/?authId=6842026a1f2d4707996fb355cea81c30&token=c3d0e26091ad31385db067c439f708dfebe6474edbfebd9338108033e9ab3b26", host: "127.0.0.1:8888"
2019/04/25 18:42:34 [error] 868#12064: *59 WSARecv() failed (10054: An existing connection was forcibly closed by the remote host) while proxying upgraded connection, client: 127.0.0.1, server: localhost, request: "GET /websockify/?authId=6842026a1f2d4707996fb355cea81c30&token=c3d0e26091ad31385db067c439f708dfebe6474edbfebd9338108033e9ab3b26 HTTP/1.1", upstream: "http://127.0.0.1:3001/websockify/?authId=6842026a1f2d4707996fb355cea81c30&token=c3d0e26091ad31385db067c439f708dfebe6474edbfebd9338108033e9ab3b26", host: "127.0.0.1:8888"
2019/04/25 18:43:26 [error] 868#12064: *62 WSARecv() failed (10054: An existing connection was forcibly closed by the remote host) while proxying upgraded connection, client: 127.0.0.1, server: localhost, request: "GET /websockify/?authId=6842026a1f2d4707996fb355cea81c30&token=c3d0e26091ad31385db067c439f708dfebe6474edbfebd9338108033e9ab3b26 HTTP/1.1", upstream: "http://127.0.0.1:3001/websockify/?authId=6842026a1f2d4707996fb355cea81c30&token=c3d0e26091ad31385db067c439f708dfebe6474edbfebd9338108033e9ab3b26", host: "127.0.0.1:8888"
2019/04/25 18:53:05 [error] 868#12064: *83 WSARecv() failed (10054: An existing connection was forcibly closed by the remote host) while proxying upgraded connection, client: 127.0.0.1, server: localhost, request: "GET /websockify/?authId=6842026a1f2d4707996fb355cea81c30&token=c3d0e26091ad31385db067c439f708dfebe6474edbfebd9338108033e9ab3b26 HTTP/1.1", upstream: "http://127.0.0.1:3001/websockify/?authId=6842026a1f2d4707996fb355cea81c30&token=c3d0e26091ad31385db067c439f708dfebe6474edbfebd9338108033e9ab3b26", host: "127.0.0.1:8888"
2019/04/25 18:53:54 [error] 868#12064: *86 WSARecv() failed (10054: An existing connection was forcibly closed by the remote host) while proxying upgraded connection, client: 127.0.0.1, server: localhost, request: "GET /websockify/?authId=6842026a1f2d4707996fb355cea81c30&token=c3d0e26091ad31385db067c439f708dfebe6474edbfebd9338108033e9ab3b26 HTTP/1.1", upstream: "http://127.0.0.1:3001/websockify/?authId=6842026a1f2d4707996fb355cea81c30&token=c3d0e26091ad31385db067c439f708dfebe6474edbfebd9338108033e9ab3b26", host: "127.0.0.1:8888"
2019/04/25 18:54:14 [error] 868#12064: *89 WSARecv() failed (10054: An existing connection was forcibly closed by the remote host) while proxying upgraded connection, client: 127.0.0.1, server: localhost, request: "GET /websockify/?authId=6842026a1f2d4707996fb355cea81c30&token=c3d0e26091ad31385db067c439f708dfebe6474edbfebd9338108033e9ab3b26 HTTP/1.1", upstream: "http://127.0.0.1:3001/websockify/?authId=6842026a1f2d4707996fb355cea81c30&token=c3d0e26091ad31385db067c439f708dfebe6474edbfebd9338108033e9ab3b26", host: "127.0.0.1:8888"
2019/04/25 19:14:06 [error] 868#12064: *131 WSARecv() failed (10054: An existing connection was forcibly closed by the remote host) while proxying upgraded connection, client: 127.0.0.1, server: localhost, request: "GET /websockify/?authId=6842026a1f2d4707996fb355cea81c30&token=c3d0e26091ad31385db067c439f708dfebe6474edbfebd9338108033e9ab3b26 HTTP/1.1", upstream: "http://127.0.0.1:3001/websockify/?authId=6842026a1f2d4707996fb355cea81c30&token=c3d0e26091ad31385db067c439f708dfebe6474edbfebd9338108033e9ab3b26", host: "127.0.0.1:8888"
2019/04/25 19:20:52 [error] 868#12064: *145 WSARecv() failed (10054: An existing connection was forcibly closed by the remote host) while proxying upgraded connection, client: 127.0.0.1, server: localhost, request: "GET /websockify/?authId=a2b5869d23904b54948b69546e4a1e74&token=c2cce78b9503c7883e286b2f588d1f8eacd608d41af6e0e286c7e651899fa312 HTTP/1.1", upstream: "http://127.0.0.1:3001/websockify/?authId=a2b5869d23904b54948b69546e4a1e74&token=c2cce78b9503c7883e286b2f588d1f8eacd608d41af6e0e286c7e651899fa312", host: "127.0.0.1:8888"
2019/04/25 19:25:19 [error] 868#12064: *168 WSARecv() failed (10054: An existing connection was forcibly closed by the remote host) while proxying upgraded connection, client: 127.0.0.1, server: localhost, request: "GET /websockify/?authId=a2b5869d23904b54948b69546e4a1e74&token=c2cce78b9503c7883e286b2f588d1f8eacd608d41af6e0e286c7e651899fa312 HTTP/1.1", upstream: "http://127.0.0.1:3001/websockify/?authId=a2b5869d23904b54948b69546e4a1e74&token=c2cce78b9503c7883e286b2f588d1f8eacd608d41af6e0e286c7e651899fa312", host: "127.0.0.1:8888"
2019/04/26 11:34:54 [error] 868#12064: *206 WSARecv() failed (10054: An existing connection was forcibly closed by the remote host) while proxying upgraded connection, client: 127.0.0.1, server: localhost, request: "GET /websockify/?authId=a2b5869d23904b54948b69546e4a1e74&token=c2cce78b9503c7883e286b2f588d1f8eacd608d41af6e0e286c7e651899fa312 HTTP/1.1", upstream: "http://127.0.0.1:3001/websockify/?authId=a2b5869d23904b54948b69546e4a1e74&token=c2cce78b9503c7883e286b2f588d1f8eacd608d41af6e0e286c7e651899fa312", host: "127.0.0.1:8888"
2019/04/26 11:37:28 [error] 868#12064: *223 WSARecv() failed (10054: An existing connection was forcibly closed by the remote host) while proxying upgraded connection, client: 127.0.0.1, server: localhost, request: "GET /websockify/?authId=f05597121603492b97406fb4523bba16&token=c2cce78b9503c7883e286b2f588d1f8e00098318a490cab393de24b57f523b1f HTTP/1.1", upstream: "http://127.0.0.1:3001/websockify/?authId=f05597121603492b97406fb4523bba16&token=c2cce78b9503c7883e286b2f588d1f8e00098318a490cab393de24b57f523b1f", host: "127.0.0.1:8888"
2019/04/26 11:38:51 [error] 868#12064: *235 WSARecv() failed (10054: An existing connection was forcibly closed by the remote host) while proxying upgraded connection, client: 127.0.0.1, server: localhost, request: "GET /websockify/?authId=f05597121603492b97406fb4523bba16&token=c2cce78b9503c7883e286b2f588d1f8e00098318a490cab393de24b57f523b1f HTTP/1.1", upstream: "http://127.0.0.1:3001/websockify/?authId=f05597121603492b97406fb4523bba16&token=c2cce78b9503c7883e286b2f588d1f8e00098318a490cab393de24b57f523b1f", host: "127.0.0.1:8888"
2019/04/26 11:39:18 [error] 868#12064: *237 WSARecv() failed (10054: An existing connection was forcibly closed by the remote host) while proxying upgraded connection, client: 127.0.0.1, server: localhost, request: "GET /websockify/?authId=f05597121603492b97406fb4523bba16&token=c2cce78b9503c7883e286b2f588d1f8e00098318a490cab393de24b57f523b1f HTTP/1.1", upstream: "http://127.0.0.1:3001/websockify/?authId=f05597121603492b97406fb4523bba16&token=c2cce78b9503c7883e286b2f588d1f8e00098318a490cab393de24b57f523b1f", host: "127.0.0.1:8888"
2019/04/26 11:39:41 [error] 868#12064: *239 WSARecv() failed (10054: An existing connection was forcibly closed by the remote host) while proxying upgraded connection, client: 127.0.0.1, server: localhost, request: "GET /websockify/?authId=f05597121603492b97406fb4523bba16&token=c2cce78b9503c7883e286b2f588d1f8e00098318a490cab393de24b57f523b1f HTTP/1.1", upstream: "http://127.0.0.1:3001/websockify/?authId=f05597121603492b97406fb4523bba16&token=c2cce78b9503c7883e286b2f588d1f8e00098318a490cab393de24b57f523b1f", host: "127.0.0.1:8888"
2019/04/26 14:21:36 [error] 868#12064: *251 CreateFile() "E:/workspace/bms_vnc/vnc/favicon.ico" failed (2: The system cannot find the file specified), client: 127.0.0.1, server: localhost, request: "GET /favicon.ico HTTP/1.1", host: "127.0.0.1:8888", referrer: "http://127.0.0.1:8888/vnc/vnc_lite.html?authId=1ad784568159453496125ed0c61c6c8c&token=c2cce78b9503c7883e286b2f588d1f8ef61b8bdeee944eac9fcd76b078c1a547"
2019/04/26 14:24:42 [error] 868#12064: *259 CreateFile() "E:/workspace/bms_vnc/vnc/favicon.ico" failed (2: The system cannot find the file specified), client: 127.0.0.1, server: localhost, request: "GET /favicon.ico HTTP/1.1", host: "127.0.0.1:8888", referrer: "http://127.0.0.1:8888/vnc/vnc_lite.html"
2019/04/26 14:30:41 [error] 868#12064: *308 WSARecv() failed (10054: An existing connection was forcibly closed by the remote host) while proxying upgraded connection, client: 127.0.0.1, server: localhost, request: "GET /websockify/?authId=23f690ba022c46029e7847746ddb8e72&token=c2cce78b9503c7883e286b2f588d1f8ef61b8bdeee944eac9fcd76b078c1a547 HTTP/1.1", upstream: "http://127.0.0.1:3001/websockify/?authId=23f690ba022c46029e7847746ddb8e72&token=c2cce78b9503c7883e286b2f588d1f8ef61b8bdeee944eac9fcd76b078c1a547", host: "127.0.0.1:8888"
2019/04/26 14:31:29 [error] 868#12064: *312 WSARecv() failed (10054: An existing connection was forcibly closed by the remote host) while proxying upgraded connection, client: 127.0.0.1, server: localhost, request: "GET /websockify/?authId=23f690ba022c46029e7847746ddb8e72&token=c2cce78b9503c7883e286b2f588d1f8ef61b8bdeee944eac9fcd76b078c1a547 HTTP/1.1", upstream: "http://127.0.0.1:3001/websockify/?authId=23f690ba022c46029e7847746ddb8e72&token=c2cce78b9503c7883e286b2f588d1f8ef61b8bdeee944eac9fcd76b078c1a547", host: "127.0.0.1:8888"
2019/04/26 14:34:47 [error] 868#12064: *317 CreateFile() "E:/workspace/bms_vnc/vnc/favicon.ico" failed (2: The system cannot find the file specified), client: 127.0.0.1, server: localhost, request: "GET /favicon.ico HTTP/1.1", host: "127.0.0.1:8888", referrer: "http://127.0.0.1:8888/vnc/vnc_lite.html?authId=23f690ba022c46029e7847746ddb8e72&token=c2cce78b9503c7883e286b2f588d1f8ef61b8bdeee944eac9fcd76b078c1a547"
2019/04/26 14:35:42 [error] 868#12064: *322 CreateFile() "E:/workspace/bms_vnc/vnc/favicon.ico" failed (2: The system cannot find the file specified), client: 127.0.0.1, server: localhost, request: "GET /favicon.ico HTTP/1.1", host: "127.0.0.1:8888", referrer: "http://127.0.0.1:8888/vnc/vnc_lite.html?authId=23f690ba022c46029e7847746ddb8e72&token=c2cce78b9503c7883e286b2f588d1f8ef61b8bdeee944eac9fcd76b078c1a547"
2019/04/26 14:36:12 [error] 868#12064: *331 WSARecv() failed (10054: An existing connection was forcibly closed by the remote host) while proxying upgraded connection, client: 127.0.0.1, server: localhost, request: "GET /websockify HTTP/1.1", upstream: "http://127.0.0.1:3001/websockify", host: "127.0.0.1:8888"
2019/04/26 14:36:49 [error] 868#12064: *321 CreateFile() "E:/workspace/bms_vnc/vnc/favicon.ico" failed (2: The system cannot find the file specified), client: 127.0.0.1, server: localhost, request: "GET /favicon.ico HTTP/1.1", host: "127.0.0.1:8888", referrer: "http://127.0.0.1:8888/vnc/vnc_lite.html?authId=af1df88d3d5f4e33b7fd23d8e373615a&token=c2cce78b9503c7883e286b2f588d1f8ef61b8bdeee944eac9fcd76b078c1a547"
2019/04/26 14:36:50 [error] 868#12064: *321 CreateFile() "E:/workspace/bms_vnc/vnc/favicon.ico" failed (2: The system cannot find the file specified), client: 127.0.0.1, server: localhost, request: "GET /favicon.ico HTTP/1.1", host: "127.0.0.1:8888", referrer: "http://127.0.0.1:8888/vnc/vnc_lite.html?authId=af1df88d3d5f4e33b7fd23d8e373615a&token=c2cce78b9503c7883e286b2f588d1f8ef61b8bdeee944eac9fcd76b078c1a547"
2019/04/26 14:36:51 [error] 868#12064: *323 CreateFile() "E:/workspace/bms_vnc/vnc/favicon.ico" failed (2: The system cannot find the file specified), client: 127.0.0.1, server: localhost, request: "GET /favicon.ico HTTP/1.1", host: "127.0.0.1:8888", referrer: "http://127.0.0.1:8888/vnc/vnc_lite.html?authId=af1df88d3d5f4e33b7fd23d8e373615a&token=c2cce78b9503c7883e286b2f588d1f8ef61b8bdeee944eac9fcd76b078c1a547"
2019/04/26 14:36:51 [error] 868#12064: *323 CreateFile() "E:/workspace/bms_vnc/vnc/favicon.ico" failed (2: The system cannot find the file specified), client: 127.0.0.1, server: localhost, request: "GET /favicon.ico HTTP/1.1", host: "127.0.0.1:8888", referrer: "http://127.0.0.1:8888/vnc/vnc_lite.html?authId=af1df88d3d5f4e33b7fd23d8e373615a&token=c2cce78b9503c7883e286b2f588d1f8ef61b8bdeee944eac9fcd76b078c1a547"
2019/04/26 14:37:17 [error] 868#12064: *323 CreateFile() "E:/workspace/bms_vnc/vnc/favicon.ico" failed (2: The system cannot find the file specified), client: 127.0.0.1, server: localhost, request: "GET /favicon.ico HTTP/1.1", host: "127.0.0.1:8888", referrer: "http://127.0.0.1:8888/vnc/vnc_lite.html?authId=af1df88d3d5f4e33b7fd23d8e373615a&token=c2cce78b9503c7883e286b2f588d1f8ef61b8bdeee944eac9fcd76b078c1a547"
2019/04/26 14:45:53 [error] 868#12064: *367 WSARecv() failed (10054: An existing connection was forcibly closed by the remote host) while proxying upgraded connection, client: 127.0.0.1, server: localhost, request: "GET /websockify HTTP/1.1", upstream: "http://127.0.0.1:3001/websockify", host: "127.0.0.1:8888"
2019/04/26 14:48:13 [error] 868#12064: *373 WSARecv() failed (10054: An existing connection was forcibly closed by the remote host) while proxying upgraded connection, client: 127.0.0.1, server: localhost, request: "GET /websockify/?authId=4567e5521593414eb0651b09b2e15874&token=c3d0e26091ad31385db067c439f708dfe1164dbc9446d92ed3c231a17c8733b2 HTTP/1.1", upstream: "http://127.0.0.1:3001/websockify/?authId=4567e5521593414eb0651b09b2e15874&token=c3d0e26091ad31385db067c439f708dfe1164dbc9446d92ed3c231a17c8733b2", host: "127.0.0.1:8888"
2019/05/22 11:44:21 [error] 16376#14756: *1 directory index of "E:/workspace/bms_vnc/vnc/" is forbidden, client: 127.0.0.1, server: localhost, request: "GET / HTTP/1.1", host: "127.0.0.1:8888"
2019/05/22 11:44:22 [error] 16376#14756: *1 CreateFile() "E:/workspace/bms_vnc/vnc/favicon.ico" failed (2: The system cannot find the file specified), client: 127.0.0.1, server: localhost, request: "GET /favicon.ico HTTP/1.1", host: "127.0.0.1:8888", referrer: "http://127.0.0.1:8888/"
2019/05/22 11:44:24 [error] 16376#14756: *1 directory index of "E:/workspace/bms_vnc/vnc/" is forbidden, client: 127.0.0.1, server: localhost, request: "GET / HTTP/1.1", host: "127.0.0.1:8888"
2019/05/22 11:46:18 [error] 17944#5980: *1 CreateFile() "E:/workspace/bms_vnc/vnc_lite.html" failed (2: The system cannot find the file specified), client: 127.0.0.1, server: localhost, request: "GET / HTTP/1.1", host: "127.0.0.1:8888"
2019/05/22 11:46:19 [error] 17944#5980: *1 CreateFile() "E:/workspace/bms_vnc/vnc_lite.html" failed (2: The system cannot find the file specified), client: 127.0.0.1, server: localhost, request: "GET / HTTP/1.1", host: "127.0.0.1:8888"
2019/05/22 11:46:19 [error] 17944#5980: *1 CreateFile() "E:/workspace/bms_vnc/vnc_lite.html" failed (2: The system cannot find the file specified), client: 127.0.0.1, server: localhost, request: "GET / HTTP/1.1", host: "127.0.0.1:8888"
2019/05/22 11:46:19 [error] 17944#5980: *1 CreateFile() "E:/workspace/bms_vnc/vnc_lite.html" failed (2: The system cannot find the file specified), client: 127.0.0.1, server: localhost, request: "GET / HTTP/1.1", host: "127.0.0.1:8888"
2019/05/22 11:46:19 [error] 17944#5980: *1 CreateFile() "E:/workspace/bms_vnc/vnc_lite.html" failed (2: The system cannot find the file specified), client: 127.0.0.1, server: localhost, request: "GET / HTTP/1.1", host: "127.0.0.1:8888"
2019/05/22 11:46:19 [error] 17944#5980: *1 CreateFile() "E:/workspace/bms_vnc/vnc_lite.html" failed (2: The system cannot find the file specified), client: 127.0.0.1, server: localhost, request: "GET / HTTP/1.1", host: "127.0.0.1:8888"
2019/05/22 11:46:19 [error] 17944#5980: *1 CreateFile() "E:/workspace/bms_vnc/vnc_lite.html" failed (2: The system cannot find the file specified), client: 127.0.0.1, server: localhost, request: "GET / HTTP/1.1", host: "127.0.0.1:8888"
2019/05/22 11:46:22 [error] 17944#5980: *1 CreateFile() "E:/workspace/bms_vnc/vnc_lite.html" failed (2: The system cannot find the file specified), client: 127.0.0.1, server: localhost, request: "GET / HTTP/1.1", host: "127.0.0.1:8888"
2019/05/22 11:46:22 [error] 17944#5980: *1 CreateFile() "E:/workspace/bms_vnc/vnc_lite.html" failed (2: The system cannot find the file specified), client: 127.0.0.1, server: localhost, request: "GET / HTTP/1.1", host: "127.0.0.1:8888"
2019/05/22 11:46:23 [error] 17944#5980: *1 CreateFile() "E:/workspace/bms_vnc/vnc_lite.html" failed (2: The system cannot find the file specified), client: 127.0.0.1, server: localhost, request: "GET / HTTP/1.1", host: "127.0.0.1:8888"
2019/05/22 11:47:12 [error] 17944#5980: *9 WSARecv() failed (10054: An existing connection was forcibly closed by the remote host) while proxying upgraded connection, client: 127.0.0.1, server: localhost, request: "GET /websockify/ HTTP/1.1", upstream: "http://127.0.0.1:3001/websockify/", host: "127.0.0.1:8888"
2019/05/22 11:47:56 [error] 17944#5980: *15 WSARecv() failed (10054: An existing connection was forcibly closed by the remote host) while proxying upgraded connection, client: 127.0.0.1, server: localhost, request: "GET /websockify/ HTTP/1.1", upstream: "http://127.0.0.1:3001/websockify/", host: "127.0.0.1:8888"
2019/05/22 11:48:24 [error] 17944#5980: *21 WSARecv() failed (10054: An existing connection was forcibly closed by the remote host) while proxying upgraded connection, client: 127.0.0.1, server: localhost, request: "GET /websockify/ HTTP/1.1", upstream: "http://127.0.0.1:3001/websockify/", host: "127.0.0.1:8888"
2019/05/22 11:48:57 [error] 17944#5980: *27 WSARecv() failed (10054: An existing connection was forcibly closed by the remote host) while proxying upgraded connection, client: 127.0.0.1, server: localhost, request: "GET /websockify/ HTTP/1.1", upstream: "http://127.0.0.1:3001/websockify/", host: "127.0.0.1:8888"
2019/05/22 11:52:22 [error] 17944#5980: *34 WSARecv() failed (10054: An existing connection was forcibly closed by the remote host) while proxying upgraded connection, client: 127.0.0.1, server: localhost, request: "GET /websockify/ HTTP/1.1", upstream: "http://127.0.0.1:3001/websockify/", host: "127.0.0.1:8888"
2019/05/22 11:53:34 [error] 17944#5980: *40 WSARecv() failed (10054: An existing connection was forcibly closed by the remote host) while proxying upgraded connection, client: 127.0.0.1, server: localhost, request: "GET /websockify/ HTTP/1.1", upstream: "http://127.0.0.1:3001/websockify/", host: "127.0.0.1:8888"
2019/05/22 11:53:59 [error] 17944#5980: *43 WSARecv() failed (10054: An existing connection was forcibly closed by the remote host) while proxying upgraded connection, client: 127.0.0.1, server: localhost, request: "GET /websockify/ HTTP/1.1", upstream: "http://127.0.0.1:3001/websockify/", host: "127.0.0.1:8888"
2019/05/22 11:54:42 [error] 17944#5980: *46 WSARecv() failed (10054: An existing connection was forcibly closed by the remote host) while proxying upgraded connection, client: 127.0.0.1, server: localhost, request: "GET /websockify/ HTTP/1.1", upstream: "http://127.0.0.1:3001/websockify/", host: "127.0.0.1:8888"
2019/05/22 11:54:59 [error] 17944#5980: *49 WSARecv() failed (10054: An existing connection was forcibly closed by the remote host) while proxying upgraded connection, client: 127.0.0.1, server: localhost, request: "GET /websockify/ HTTP/1.1", upstream: "http://127.0.0.1:3001/websockify/", host: "127.0.0.1:8888"
2019/05/22 13:52:33 [error] 17944#5980: *66 WSARecv() failed (10054: An existing connection was forcibly closed by the remote host) while proxying upgraded connection, client: 127.0.0.1, server: localhost, request: "GET /websockify/?authId=e50d2bc067be4eadb53c35e9d9658c45&token=c2cce78b9503c7883e286b2f588d1f8e5206a0c21d7e46325452fb1036f90f72 HTTP/1.1", upstream: "http://127.0.0.1:3001/websockify/?authId=e50d2bc067be4eadb53c35e9d9658c45&token=c2cce78b9503c7883e286b2f588d1f8e5206a0c21d7e46325452fb1036f90f72", host: "127.0.0.1:8888"
2019/05/22 13:52:53 [error] 17944#5980: *68 WSARecv() failed (10054: An existing connection was forcibly closed by the remote host) while proxying upgraded connection, client: 127.0.0.1, server: localhost, request: "GET /websockify/?authId=e50d2bc067be4eadb53c35e9d9658c45&token=c2cce78b9503c7883e286b2f588d1f8e5206a0c21d7e46325452fb1036f90f72 HTTP/1.1", upstream: "http://127.0.0.1:3001/websockify/?authId=e50d2bc067be4eadb53c35e9d9658c45&token=c2cce78b9503c7883e286b2f588d1f8e5206a0c21d7e46325452fb1036f90f72", host: "127.0.0.1:8888"
2019/08/14 15:55:15 [error] 10416#23036: *4 CreateFile() "E:/workspace/bms_vnc/vnc/favicon.ico" failed (2: The system cannot find the file specified), client: 127.0.0.1, server: localhost, request: "GET /favicon.ico HTTP/1.1", host: "127.0.0.1:8888", referrer: "http://127.0.0.1:8888/vnc/vnc_lite.html"
2019/08/14 15:56:30 [error] 10416#23036: *15 WSARecv() failed (10054: An existing connection was forcibly closed by the remote host) while proxying upgraded connection, client: 127.0.0.1, server: localhost, request: "GET /websockify/ HTTP/1.1", upstream: "http://127.0.0.1:3001/websockify/", host: "127.0.0.1:8888"
2019/08/14 16:45:02 [error] 10416#23036: *46 WSARecv() failed (10054: An existing connection was forcibly closed by the remote host) while proxying upgraded connection, client: 127.0.0.1, server: localhost, request: "GET /websockify/ HTTP/1.1", upstream: "http://127.0.0.1:3001/websockify/", host: "127.0.0.1:8888"
2019/08/14 16:45:09 [error] 10416#23036: *49 WSARecv() failed (10054: An existing connection was forcibly closed by the remote host) while proxying upgraded connection, client: 127.0.0.1, server: localhost, request: "GET /websockify/ HTTP/1.1", upstream: "http://127.0.0.1:3001/websockify/", host: "127.0.0.1:8888"
2019/08/14 16:45:34 [error] 10416#23036: *52 WSARecv() failed (10054: An existing connection was forcibly closed by the remote host) while proxying upgraded connection, client: 127.0.0.1, server: localhost, request: "GET /websockify/ HTTP/1.1", upstream: "http://127.0.0.1:3001/websockify/", host: "127.0.0.1:8888"
2019/08/14 17:40:00 [error] 12508#40592: *60 WSARecv() failed (10054: An existing connection was forcibly closed by the remote host) while proxying upgraded connection, client: 127.0.0.1, server: localhost, request: "GET /websockify/ HTTP/1.1", upstream: "http://127.0.0.1:3001/websockify/", host: "127.0.0.1:8888"
2019/08/14 17:40:06 [error] 12508#40592: *62 WSARecv() failed (10054: An existing connection was forcibly closed by the remote host) while proxying upgraded connection, client: 127.0.0.1, server: localhost, request: "GET /websockify/ HTTP/1.1", upstream: "http://127.0.0.1:3001/websockify/", host: "127.0.0.1:8888"
2019/08/14 17:52:58 [error] 12508#40592: *77 WSARecv() failed (10054: An existing connection was forcibly closed by the remote host) while proxying upgraded connection, client: 127.0.0.1, server: localhost, request: "GET /websockify/ HTTP/1.1", upstream: "http://127.0.0.1:3001/websockify/", host: "127.0.0.1:8888"
2019/08/14 17:57:03 [error] 12508#40592: *87 WSARecv() failed (10054: An existing connection was forcibly closed by the remote host) while proxying upgraded connection, client: 127.0.0.1, server: localhost, request: "GET /websockify/ HTTP/1.1", upstream: "http://127.0.0.1:3001/websockify/", host: "127.0.0.1:8888"
2019/11/27 10:29:41 [error] 14812#53976: *1 CreateFile() "E:/workspace/bms_vnc/vnc_lite.html" failed (2: The system cannot find the file specified), client: 127.0.0.1, server: localhost, request: "GET / HTTP/1.1", host: "localhost:8888"
2019/11/27 10:29:42 [error] 14812#53976: *1 CreateFile() "E:/workspace/bms_vnc/vnc/favicon.ico" failed (2: The system cannot find the file specified), client: 127.0.0.1, server: localhost, request: "GET /favicon.ico HTTP/1.1", host: "localhost:8888", referrer: "http://localhost:8888/"
2019/12/17 10:29:15 [emerg] 14868#16508: unexpected "}" in E:\nginx-1.9.1/conf/nginx.conf:75
2019/12/17 10:31:37 [emerg] 18620#22376: unexpected "}" in E:\nginx-1.9.1/conf/nginx.conf:75
2019/12/17 10:32:24 [emerg] 21020#17696: unexpected "}" in E:\nginx-1.9.1/conf/nginx.conf:75
2019/12/17 10:34:07 [emerg] 15460#12456: unexpected "}" in E:\nginx-1.9.1/conf/nginx.conf:75
2020/01/07 15:42:48 [emerg] 13676#13208: unexpected "}" in E:\nginx-1.9.1/conf/nginx.conf:75
2020/01/07 15:47:03 [error] 15804#3304: *1 CreateFile() "E:/workspace/bms_vnc/vnc_lite.html" failed (2: The system cannot find the file specified), client: 127.0.0.1, server: localhost, request: "GET / HTTP/1.1", host: "127.0.0.1:8888"
2020/01/07 15:47:04 [error] 15804#3304: *1 CreateFile() "E:/workspace/bms_vnc/vnc/favicon.ico" failed (2: The system cannot find the file specified), client: 127.0.0.1, server: localhost, request: "GET /favicon.ico HTTP/1.1", host: "127.0.0.1:8888", referrer: "http://127.0.0.1:8888/"
2020/01/07 15:47:04 [error] 15804#3304: *1 CreateFile() "E:/workspace/bms_vnc/vnc_lite.html" failed (2: The system cannot find the file specified), client: 127.0.0.1, server: localhost, request: "GET / HTTP/1.1", host: "127.0.0.1:8888"
2020/01/07 15:47:05 [error] 15804#3304: *1 CreateFile() "E:/workspace/bms_vnc/vnc_lite.html" failed (2: The system cannot find the file specified), client: 127.0.0.1, server: localhost, request: "GET / HTTP/1.1", host: "127.0.0.1:8888"
2020/01/07 15:47:54 [error] 15804#3304: *1 CreateFile() "E:/workspace/bms_vnc/vnc_lite.html" failed (2: The system cannot find the file specified), client: 127.0.0.1, server: localhost, request: "GET / HTTP/1.1", host: "127.0.0.1:8888"
2020/01/07 15:47:55 [error] 15804#3304: *1 CreateFile() "E:/workspace/bms_vnc/vnc_lite.html" failed (2: The system cannot find the file specified), client: 127.0.0.1, server: localhost, request: "GET / HTTP/1.1", host: "127.0.0.1:8888"
2020/01/07 15:47:55 [error] 15804#3304: *1 CreateFile() "E:/workspace/bms_vnc/vnc_lite.html" failed (2: The system cannot find the file specified), client: 127.0.0.1, server: localhost, request: "GET / HTTP/1.1", host: "127.0.0.1:8888"
2020/01/07 15:48:05 [error] 15804#3304: *1 CreateFile() "E:/workspace/bms_vnc/vnc-lite.html" failed (2: The system cannot find the file specified), client: 127.0.0.1, server: localhost, request: "GET /vnc-lite.html HTTP/1.1", host: "127.0.0.1:8888"
2020/01/07 15:48:08 [error] 15804#3304: *1 CreateFile() "E:/workspace/bms_vnc/vnc-lite.html" failed (2: The system cannot find the file specified), client: 127.0.0.1, server: localhost, request: "GET /vnc-lite.html HTTP/1.1", host: "127.0.0.1:8888"
2020/01/07 15:48:58 [error] 15804#3304: *1 CreateFile() "E:/workspace/bms_vnc/vnc-lite.html" failed (2: The system cannot find the file specified), client: 127.0.0.1, server: localhost, request: "GET /vnc-lite.html HTTP/1.1", host: "127.0.0.1:8888"
2020/01/07 15:48:59 [error] 15804#3304: *1 CreateFile() "E:/workspace/bms_vnc/vnc-lite.html" failed (2: The system cannot find the file specified), client: 127.0.0.1, server: localhost, request: "GET /vnc-lite.html HTTP/1.1", host: "127.0.0.1:8888"
2020/01/07 15:48:59 [error] 15804#3304: *1 CreateFile() "E:/workspace/bms_vnc/vnc-lite.html" failed (2: The system cannot find the file specified), client: 127.0.0.1, server: localhost, request: "GET /vnc-lite.html HTTP/1.1", host: "127.0.0.1:8888"
2020/01/07 15:48:59 [error] 15804#3304: *1 CreateFile() "E:/workspace/bms_vnc/vnc-lite.html" failed (2: The system cannot find the file specified), client: 127.0.0.1, server: localhost, request: "GET /vnc-lite.html HTTP/1.1", host: "127.0.0.1:8888"
2020/01/07 15:49:00 [error] 15804#3304: *1 CreateFile() "E:/workspace/bms_vnc/vnc-lite.html" failed (2: The system cannot find the file specified), client: 127.0.0.1, server: localhost, request: "GET /vnc-lite.html HTTP/1.1", host: "127.0.0.1:8888"
2020/01/07 15:49:45 [error] 15804#3304: *6 CreateFile() "E:/workspace/bms_vnc/vnc/vncproxy/module/vm.dao.js" failed (3: The system cannot find the path specified), client: 127.0.0.1, server: localhost, request: "GET /vnc/vncproxy/module/vm.dao.js HTTP/1.1", host: "127.0.0.1:8888", referrer: "http://127.0.0.1:8888/vnc/?authId=6c90c590bd5f471c8af89e51cb1f4b9b&token=2fd11b446d275d45c4363960e55fe2516ad9103b5435bc2cc76be3a7d35e3fdd"
2020/01/07 15:50:40 [error] 15804#3304: *1 CreateFile() "E:/workspace/bms_vnc/vnc/vncproxy/module/vm.dao.js" failed (3: The system cannot find the path specified), client: 127.0.0.1, server: localhost, request: "GET /vnc/vncproxy/module/vm.dao.js HTTP/1.1", host: "127.0.0.1:8888", referrer: "http://127.0.0.1:8888/vnc/?authId=6c90c590bd5f471c8af89e51cb1f4b9b&token=2fd11b446d275d45c4363960e55fe2516ad9103b5435bc2cc76be3a7d35e3fdd"
2020/01/07 15:50:41 [error] 15804#3304: *1 CreateFile() "E:/workspace/bms_vnc/vnc/vncproxy/module/vm.dao.js" failed (3: The system cannot find the path specified), client: 127.0.0.1, server: localhost, request: "GET /vnc/vncproxy/module/vm.dao.js HTTP/1.1", host: "127.0.0.1:8888", referrer: "http://127.0.0.1:8888/vnc/?authId=6c90c590bd5f471c8af89e51cb1f4b9b&token=2fd11b446d275d45c4363960e55fe2516ad9103b5435bc2cc76be3a7d35e3fdd"
2020/01/07 15:50:49 [error] 15804#3304: *9 CreateFile() "E:/workspace/bms_vnc/vnc/vncproxy/module/vm.dao.js" failed (3: The system cannot find the path specified), client: 127.0.0.1, server: localhost, request: "GET /vnc/vncproxy/module/vm.dao.js HTTP/1.1", host: "127.0.0.1:8888", referrer: "http://127.0.0.1:8888/vnc/?authId=6c90c590bd5f471c8af89e51cb1f4b9b&token=2fd11b446d275d45c4363960e55fe2516ad9103b5435bc2cc76be3a7d35e3fdd"
2020/01/07 15:50:50 [error] 15804#3304: *10 CreateFile() "E:/workspace/bms_vnc/vnc/vncproxy/module/vm.dao.js" failed (3: The system cannot find the path specified), client: 127.0.0.1, server: localhost, request: "GET /vnc/vncproxy/module/vm.dao.js HTTP/1.1", host: "127.0.0.1:8888", referrer: "http://127.0.0.1:8888/vnc/?authId=6c90c590bd5f471c8af89e51cb1f4b9b&token=2fd11b446d275d45c4363960e55fe2516ad9103b5435bc2cc76be3a7d35e3fdd"
2020/01/07 15:50:50 [error] 15804#3304: *10 CreateFile() "E:/workspace/bms_vnc/vnc/vncproxy/module/vm.dao.js" failed (3: The system cannot find the path specified), client: 127.0.0.1, server: localhost, request: "GET /vnc/vncproxy/module/vm.dao.js HTTP/1.1", host: "127.0.0.1:8888", referrer: "http://127.0.0.1:8888/vnc/?authId=6c90c590bd5f471c8af89e51cb1f4b9b&token=2fd11b446d275d45c4363960e55fe2516ad9103b5435bc2cc76be3a7d35e3fdd"
2020/01/07 15:50:50 [error] 15804#3304: *10 CreateFile() "E:/workspace/bms_vnc/vnc/vncproxy/module/vm.dao.js" failed (3: The system cannot find the path specified), client: 127.0.0.1, server: localhost, request: "GET /vnc/vncproxy/module/vm.dao.js HTTP/1.1", host: "127.0.0.1:8888", referrer: "http://127.0.0.1:8888/vnc/?authId=6c90c590bd5f471c8af89e51cb1f4b9b&token=2fd11b446d275d45c4363960e55fe2516ad9103b5435bc2cc76be3a7d35e3fdd"
2020/01/07 15:50:51 [error] 15804#3304: *10 CreateFile() "E:/workspace/bms_vnc/vnc/vncproxy/module/vm.dao.js" failed (3: The system cannot find the path specified), client: 127.0.0.1, server: localhost, request: "GET /vnc/vncproxy/module/vm.dao.js HTTP/1.1", host: "127.0.0.1:8888", referrer: "http://127.0.0.1:8888/vnc/?authId=6c90c590bd5f471c8af89e51cb1f4b9b&token=2fd11b446d275d45c4363960e55fe2516ad9103b5435bc2cc76be3a7d35e3fdd"
2020/01/07 16:32:44 [error] 15804#3304: *11 CreateFile() "E:/workspace/bms_vnc/vnc/vncproxy/module/vm.dao.js" failed (3: The system cannot find the path specified), client: 127.0.0.1, server: localhost, request: "GET /vnc/vncproxy/module/vm.dao.js HTTP/1.1", host: "127.0.0.1:8888", referrer: "http://127.0.0.1:8888/vnc/?authId=6c90c590bd5f471c8af89e51cb1f4b9b&token=2fd11b446d275d45c4363960e55fe2516ad9103b5435bc2cc76be3a7d35e3fdd"
2020/01/07 16:32:45 [error] 15804#3304: *11 CreateFile() "E:/workspace/bms_vnc/vnc/vncproxy/module/vm.dao.js" failed (3: The system cannot find the path specified), client: 127.0.0.1, server: localhost, request: "GET /vnc/vncproxy/module/vm.dao.js HTTP/1.1", host: "127.0.0.1:8888", referrer: "http://127.0.0.1:8888/vnc/?authId=6c90c590bd5f471c8af89e51cb1f4b9b&token=2fd11b446d275d45c4363960e55fe2516ad9103b5435bc2cc76be3a7d35e3fdd"
2020/01/07 16:32:45 [error] 15804#3304: *11 CreateFile() "E:/workspace/bms_vnc/vnc/vncproxy/module/vm.dao.js" failed (3: The system cannot find the path specified), client: 127.0.0.1, server: localhost, request: "GET /vnc/vncproxy/module/vm.dao.js HTTP/1.1", host: "127.0.0.1:8888", referrer: "http://127.0.0.1:8888/vnc/?authId=6c90c590bd5f471c8af89e51cb1f4b9b&token=2fd11b446d275d45c4363960e55fe2516ad9103b5435bc2cc76be3a7d35e3fdd"
2020/01/07 16:44:30 [error] 15804#3304: *14 CreateFile() "E:/workspace/bms_vnc/vnc/vncproxy/module/vm.dao.js" failed (3: The system cannot find the path specified), client: 127.0.0.1, server: localhost, request: "GET /vnc/vncproxy/module/vm.dao.js HTTP/1.1", host: "127.0.0.1:8888", referrer: "http://127.0.0.1:8888/vnc/?authId=6c90c590bd5f471c8af89e51cb1f4b9b&token=2fd11b446d275d45c4363960e55fe2516ad9103b5435bc2cc76be3a7d35e3fdd"
2020/01/07 16:44:36 [error] 15804#3304: *14 CreateFile() "E:/workspace/bms_vnc/vnc/vncproxy/module/vm.dao.js" failed (3: The system cannot find the path specified), client: 127.0.0.1, server: localhost, request: "GET /vnc/vncproxy/module/vm.dao.js HTTP/1.1", host: "127.0.0.1:8888"
2020/01/07 16:44:39 [error] 15804#3304: *14 CreateFile() "E:/workspace/bms_vnc/vnc/vncproxy/module/vm.dao.js" failed (3: The system cannot find the path specified), client: 127.0.0.1, server: localhost, request: "GET /vnc/vncproxy/module/vm.dao.js HTTP/1.1", host: "127.0.0.1:8888"
2020/01/07 16:45:00 [error] 15804#3304: *14 CreateFile() "E:/workspace/bms_vnc/vnc/service/vm" failed (2: The system cannot find the file specified), client: 127.0.0.1, server: localhost, request: "GET /service/vm HTTP/1.1", host: "127.0.0.1:8888", referrer: "http://127.0.0.1:8888/vnc/?authId=6c90c590bd5f471c8af89e51cb1f4b9b&token=2fd11b446d275d45c4363960e55fe2516ad9103b5435bc2cc76be3a7d35e3fdd"
2020/01/07 16:47:12 [error] 15804#3304: *14 CreateFile() "E:/workspace/bms_vnc/vnc/service/vm" failed (2: The system cannot find the file specified), client: 127.0.0.1, server: localhost, request: "GET /service/vm HTTP/1.1", host: "127.0.0.1:8888", referrer: "http://127.0.0.1:8888/vnc/?authId=6c90c590bd5f471c8af89e51cb1f4b9b&token=2fd11b446d275d45c4363960e55fe2516ad9103b5435bc2cc76be3a7d35e3fdd"
2020/01/07 16:47:13 [error] 15804#3304: *14 CreateFile() "E:/workspace/bms_vnc/vnc/service/vm" failed (2: The system cannot find the file specified), client: 127.0.0.1, server: localhost, request: "GET /service/vm HTTP/1.1", host: "127.0.0.1:8888", referrer: "http://127.0.0.1:8888/vnc/?authId=6c90c590bd5f471c8af89e51cb1f4b9b&token=2fd11b446d275d45c4363960e55fe2516ad9103b5435bc2cc76be3a7d35e3fdd"
2020/01/07 16:47:14 [error] 15804#3304: *14 CreateFile() "E:/workspace/bms_vnc/vnc/service/vm" failed (2: The system cannot find the file specified), client: 127.0.0.1, server: localhost, request: "GET /service/vm HTTP/1.1", host: "127.0.0.1:8888", referrer: "http://127.0.0.1:8888/vnc/?authId=6c90c590bd5f471c8af89e51cb1f4b9b&token=2fd11b446d275d45c4363960e55fe2516ad9103b5435bc2cc76be3a7d35e3fdd"
2020/01/07 16:47:14 [error] 15804#3304: *14 CreateFile() "E:/workspace/bms_vnc/vnc/service/vm" failed (2: The system cannot find the file specified), client: 127.0.0.1, server: localhost, request: "GET /service/vm HTTP/1.1", host: "127.0.0.1:8888", referrer: "http://127.0.0.1:8888/vnc/?authId=6c90c590bd5f471c8af89e51cb1f4b9b&token=2fd11b446d275d45c4363960e55fe2516ad9103b5435bc2cc76be3a7d35e3fdd"
2020/01/07 16:47:15 [error] 15804#3304: *14 CreateFile() "E:/workspace/bms_vnc/vnc/service/vm" failed (2: The system cannot find the file specified), client: 127.0.0.1, server: localhost, request: "GET /service/vm HTTP/1.1", host: "127.0.0.1:8888", referrer: "http://127.0.0.1:8888/vnc/?authId=6c90c590bd5f471c8af89e51cb1f4b9b&token=2fd11b446d275d45c4363960e55fe2516ad9103b5435bc2cc76be3a7d35e3fdd"
2020/01/07 16:47:45 [error] 15804#3304: *14 CreateFile() "E:/workspace/bms_vnc/vnc/service/vm" failed (2: The system cannot find the file specified), client: 127.0.0.1, server: localhost, request: "GET /vnc/service/vm HTTP/1.1", host: "127.0.0.1:8888", referrer: "http://127.0.0.1:8888/vnc/?authId=6c90c590bd5f471c8af89e51cb1f4b9b&token=2fd11b446d275d45c4363960e55fe2516ad9103b5435bc2cc76be3a7d35e3fdd"
2020/01/07 16:47:46 [error] 15804#3304: *14 CreateFile() "E:/workspace/bms_vnc/vnc/service/vm" failed (2: The system cannot find the file specified), client: 127.0.0.1, server: localhost, request: "GET /vnc/service/vm HTTP/1.1", host: "127.0.0.1:8888", referrer: "http://127.0.0.1:8888/vnc/?authId=6c90c590bd5f471c8af89e51cb1f4b9b&token=2fd11b446d275d45c4363960e55fe2516ad9103b5435bc2cc76be3a7d35e3fdd"
2020/01/07 16:47:47 [error] 15804#3304: *14 CreateFile() "E:/workspace/bms_vnc/vnc/service/vm" failed (2: The system cannot find the file specified), client: 127.0.0.1, server: localhost, request: "GET /vnc/service/vm HTTP/1.1", host: "127.0.0.1:8888", referrer: "http://127.0.0.1:8888/vnc/?authId=6c90c590bd5f471c8af89e51cb1f4b9b&token=2fd11b446d275d45c4363960e55fe2516ad9103b5435bc2cc76be3a7d35e3fdd"
2020/01/07 16:47:47 [error] 15804#3304: *14 CreateFile() "E:/workspace/bms_vnc/vnc/service/vm" failed (2: The system cannot find the file specified), client: 127.0.0.1, server: localhost, request: "GET /vnc/service/vm HTTP/1.1", host: "127.0.0.1:8888", referrer: "http://127.0.0.1:8888/vnc/?authId=6c90c590bd5f471c8af89e51cb1f4b9b&token=2fd11b446d275d45c4363960e55fe2516ad9103b5435bc2cc76be3a7d35e3fdd"
2020/01/07 17:02:03 [error] 15804#3304: *25 CreateFile() "E:/workspace/bms_vnc/vnc/utils/axios.min.map" failed (2: The system cannot find the file specified), client: 127.0.0.1, server: localhost, request: "GET /vnc/utils/axios.min.map HTTP/1.1", host: "127.0.0.1:8888"
2020/01/07 17:02:03 [error] 15804#3304: *25 CreateFile() "E:/workspace/bms_vnc/vnc/utils/axios.min.map" failed (2: The system cannot find the file specified), client: 127.0.0.1, server: localhost, request: "GET /vnc/utils/axios.min.map HTTP/1.1", host: "127.0.0.1:8888"
2020/01/07 17:04:17 [error] 15804#3304: *30 CreateFile() "E:/workspace/bms_vnc/vnc/utils/axios.min.map" failed (2: The system cannot find the file specified), client: 127.0.0.1, server: localhost, request: "GET /vnc/utils/axios.min.map HTTP/1.1", host: "127.0.0.1:8888"
2020/01/07 17:04:18 [error] 15804#3304: *30 CreateFile() "E:/workspace/bms_vnc/vnc/utils/axios.min.map" failed (2: The system cannot find the file specified), client: 127.0.0.1, server: localhost, request: "GET /vnc/utils/axios.min.map HTTP/1.1", host: "127.0.0.1:8888"
2020/01/07 17:10:45 [error] 15804#3304: *32 CreateFile() "E:/workspace/bms_vnc/vnc/utils/axios.min.map" failed (2: The system cannot find the file specified), client: 127.0.0.1, server: localhost, request: "GET /vnc/utils/axios.min.map HTTP/1.1", host: "127.0.0.1:8888"
2020/01/07 17:11:45 [error] 15804#3304: *34 upstream timed out (10060: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond) while connecting to upstream, client: 127.0.0.1, server: localhost, request: "GET /websockify/?authId=6c90c590bd5f471c8af89e51cb1f4b9b&token=2fd11b446d275d45c4363960e55fe2516ad9103b5435bc2cc76be3a7d35e3fdd HTTP/1.1", upstream: "http://127.0.0.1:3001/websockify/?authId=6c90c590bd5f471c8af89e51cb1f4b9b&token=2fd11b446d275d45c4363960e55fe2516ad9103b5435bc2cc76be3a7d35e3fdd", host: "127.0.0.1:8888"
2020/01/07 17:11:54 [error] 15804#3304: *32 CreateFile() "E:/workspace/bms_vnc/vnc/utils/axios.min.map" failed (2: The system cannot find the file specified), client: 127.0.0.1, server: localhost, request: "GET /vnc/utils/axios.min.map HTTP/1.1", host: "127.0.0.1:8888"
2020/01/07 17:12:54 [error] 15804#3304: *37 upstream timed out (10060: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond) while connecting to upstream, client: 127.0.0.1, server: localhost, request: "GET /websockify/?authId=6c90c590bd5f471c8af89e51cb1f4b9b&token=2fd11b446d275d45c4363960e55fe2516ad9103b5435bc2cc76be3a7d35e3fdd HTTP/1.1", upstream: "http://127.0.0.1:3001/websockify/?authId=6c90c590bd5f471c8af89e51cb1f4b9b&token=2fd11b446d275d45c4363960e55fe2516ad9103b5435bc2cc76be3a7d35e3fdd", host: "127.0.0.1:8888"
2020/01/07 17:14:28 [error] 15804#3304: *39 CreateFile() "E:/workspace/bms_vnc/vnc/utils/axios.min.map" failed (2: The system cannot find the file specified), client: 127.0.0.1, server: localhost, request: "GET /vnc/utils/axios.min.map HTTP/1.1", host: "127.0.0.1:8888"
2020/01/07 17:15:28 [error] 15804#3304: *41 upstream timed out (10060: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond) while connecting to upstream, client: 127.0.0.1, server: localhost, request: "GET /websockify/?authId=6c90c590bd5f471c8af89e51cb1f4b9b&token=2fd11b446d275d45c4363960e55fe2516ad9103b5435bc2cc76be3a7d35e3fdd HTTP/1.1", upstream: "http://127.0.0.1:3001/websockify/?authId=6c90c590bd5f471c8af89e51cb1f4b9b&token=2fd11b446d275d45c4363960e55fe2516ad9103b5435bc2cc76be3a7d35e3fdd", host: "127.0.0.1:8888"
2020/01/07 17:16:46 [error] 15804#3304: *43 CreateFile() "E:/workspace/bms_vnc/vnc/utils/axios.min.map" failed (2: The system cannot find the file specified), client: 127.0.0.1, server: localhost, request: "GET /vnc/utils/axios.min.map HTTP/1.1", host: "127.0.0.1:8888"
2020/01/07 17:17:46 [error] 15804#3304: *45 upstream timed out (10060: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond) while connecting to upstream, client: 127.0.0.1, server: localhost, request: "GET /websockify/?authId=6c90c590bd5f471c8af89e51cb1f4b9b&token=2fd11b446d275d45c4363960e55fe2516ad9103b5435bc2cc76be3a7d35e3fdd HTTP/1.1", upstream: "http://127.0.0.1:3001/websockify/?authId=6c90c590bd5f471c8af89e51cb1f4b9b&token=2fd11b446d275d45c4363960e55fe2516ad9103b5435bc2cc76be3a7d35e3fdd", host: "127.0.0.1:8888"
2020/01/07 17:18:58 [error] 15804#3304: *47 CreateFile() "E:/workspace/bms_vnc/vnc/utils/axios.min.map" failed (2: The system cannot find the file specified), client: 127.0.0.1, server: localhost, request: "GET /vnc/utils/axios.min.map HTTP/1.1", host: "127.0.0.1:8888"
2020/01/07 17:19:17 [error] 15804#3304: *47 CreateFile() "E:/workspace/bms_vnc/vnc/utils/axios.min.map" failed (2: The system cannot find the file specified), client: 127.0.0.1, server: localhost, request: "GET /vnc/utils/axios.min.map HTTP/1.1", host: "127.0.0.1:8888"
2020/01/07 17:20:18 [error] 15804#3304: *50 upstream timed out (10060: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond) while connecting to upstream, client: 127.0.0.1, server: localhost, request: "GET /websockify/?authId=6c90c590bd5f471c8af89e51cb1f4b9b&token=2fd11b446d275d45c4363960e55fe2516ad9103b5435bc2cc76be3a7d35e3fdd HTTP/1.1", upstream: "http://127.0.0.1:3001/websockify/?authId=6c90c590bd5f471c8af89e51cb1f4b9b&token=2fd11b446d275d45c4363960e55fe2516ad9103b5435bc2cc76be3a7d35e3fdd", host: "127.0.0.1:8888"
2020/01/14 14:47:18 [error] 16388#10648: *4 CreateFile() "E:/workspace/bms_vnc/vnc/favicon.ico" failed (2: The system cannot find the file specified), client: 127.0.0.1, server: localhost, request: "GET /favicon.ico HTTP/1.1", host: "127.0.0.1:8888", referrer: "http://127.0.0.1:8888/vnc/?authId=6c90c590bd5f471c8af89e51cb1f4b9b&token=2fd11b446d275d45c4363960e55fe2516ad9103b5435bc2cc76be3a7d35e3fdd"
2020/01/14 14:47:22 [error] 16388#10648: *4 CreateFile() "E:/workspace/bms_vnc/vnc/utils/axios.min.map" failed (2: The system cannot find the file specified), client: 127.0.0.1, server: localhost, request: "GET /vnc/utils/axios.min.map HTTP/1.1", host: "127.0.0.1:8888"
2020/01/14 14:47:26 [error] 16388#10648: *4 CreateFile() "E:/workspace/bms_vnc/vnc/utils/axios.min.map" failed (2: The system cannot find the file specified), client: 127.0.0.1, server: localhost, request: "GET /vnc/utils/axios.min.map HTTP/1.1", host: "127.0.0.1:8888"
2020/01/14 14:47:45 [error] 16388#10648: *4 CreateFile() "E:/workspace/bms_vnc/vnc/utils/axios.min.map" failed (2: The system cannot find the file specified), client: 127.0.0.1, server: localhost, request: "GET /vnc/utils/axios.min.map HTTP/1.1", host: "127.0.0.1:8888"
2020/01/14 14:48:45 [error] 16388#10648: *11 upstream timed out (10060: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond) while connecting to upstream, client: 127.0.0.1, server: localhost, request: "GET /websockify/?authId=ff41a86ca39044fe9fb6947e863869c8&token=2fd11b446d275d45c4363960e55fe2513f13d422c9db50f21139b73fa5a6788c HTTP/1.1", upstream: "http://127.0.0.1:3001/websockify/?authId=ff41a86ca39044fe9fb6947e863869c8&token=2fd11b446d275d45c4363960e55fe2513f13d422c9db50f21139b73fa5a6788c", host: "127.0.0.1:8888"
2020/01/14 14:49:11 [error] 16388#10648: *4 CreateFile() "E:/workspace/bms_vnc/vnc/utils/axios.min.map" failed (2: The system cannot find the file specified), client: 127.0.0.1, server: localhost, request: "GET /vnc/utils/axios.min.map HTTP/1.1", host: "127.0.0.1:8888"
2020/01/14 14:50:12 [error] 16388#10648: *13 upstream timed out (10060: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond) while connecting to upstream, client: 127.0.0.1, server: localhost, request: "GET /websockify/?authId=ff41a86ca39044fe9fb6947e863869c8&token=2fd11b446d275d45c4363960e55fe2513f13d422c9db50f21139b73fa5a6788c HTTP/1.1", upstream: "http://127.0.0.1:3001/websockify/?authId=ff41a86ca39044fe9fb6947e863869c8&token=2fd11b446d275d45c4363960e55fe2513f13d422c9db50f21139b73fa5a6788c", host: "127.0.0.1:8888"
2020/01/14 14:52:24 [error] 16388#10648: *15 CreateFile() "E:/workspace/bms_vnc/vnc/utils/axios.min.map" failed (2: The system cannot find the file specified), client: 127.0.0.1, server: localhost, request: "GET /vnc/utils/axios.min.map HTTP/1.1", host: "127.0.0.1:8888"
2020/01/14 14:53:24 [error] 16388#10648: *15 upstream timed out (10060: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond) while connecting to upstream, client: 127.0.0.1, server: localhost, request: "GET /bms/v1/vnc/ff41a86ca39044fe9fb6947e863869c8 HTTP/1.1", upstream: "http://10.13.103.43:8088/bms/v1/vnc/ff41a86ca39044fe9fb6947e863869c8", host: "127.0.0.1:8888", referrer: "http://127.0.0.1:8888/vnc/?authId=ff41a86ca39044fe9fb6947e863869c8&token=2fd11b446d275d45c4363960e55fe2513f13d422c9db50f21139b73fa5a6788c"
2020/01/14 14:53:25 [error] 16388#10648: *18 upstream timed out (10060: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond) while connecting to upstream, client: 127.0.0.1, server: localhost, request: "GET /websockify/?authId=ff41a86ca39044fe9fb6947e863869c8&token=2fd11b446d275d45c4363960e55fe2513f13d422c9db50f21139b73fa5a6788c HTTP/1.1", upstream: "http://127.0.0.1:3001/websockify/?authId=ff41a86ca39044fe9fb6947e863869c8&token=2fd11b446d275d45c4363960e55fe2513f13d422c9db50f21139b73fa5a6788c", host: "127.0.0.1:8888"
2020/01/14 14:54:30 [error] 16388#10648: *15 CreateFile() "E:/workspace/bms_vnc/vnc/utils/axios.min.map" failed (2: The system cannot find the file specified), client: 127.0.0.1, server: localhost, request: "GET /vnc/utils/axios.min.map HTTP/1.1", host: "127.0.0.1:8888"
2020/01/14 14:55:30 [error] 16388#10648: *15 upstream timed out (10060: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond) while connecting to upstream, client: 127.0.0.1, server: localhost, request: "GET /bms/v1/vnc/ff41a86ca39044fe9fb6947e863869c8 HTTP/1.1", upstream: "http://10.13.103.43:8088/bms/v1/vnc/ff41a86ca39044fe9fb6947e863869c8", host: "127.0.0.1:8888", referrer: "http://127.0.0.1:8888/vnc/?authId=ff41a86ca39044fe9fb6947e863869c8&token=2fd11b446d275d45c4363960e55fe2513f13d422c9db50f21139b73fa5a6788c"
2020/01/14 14:55:30 [error] 16388#10648: *22 upstream timed out (10060: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond) while connecting to upstream, client: 127.0.0.1, server: localhost, request: "GET /websockify/?authId=ff41a86ca39044fe9fb6947e863869c8&token=2fd11b446d275d45c4363960e55fe2513f13d422c9db50f21139b73fa5a6788c HTTP/1.1", upstream: "http://127.0.0.1:3001/websockify/?authId=ff41a86ca39044fe9fb6947e863869c8&token=2fd11b446d275d45c4363960e55fe2513f13d422c9db50f21139b73fa5a6788c", host: "127.0.0.1:8888"
2020/01/14 14:55:34 [error] 16388#10648: *24 CreateFile() "E:/workspace/bms_vnc/vnc/utils/axios.min.map" failed (2: The system cannot find the file specified), client: 127.0.0.1, server: localhost, request: "GET /vnc/utils/axios.min.map HTTP/1.1", host: "127.0.0.1:8888"
2020/01/14 14:56:16 [error] 16388#10648: *29 CreateFile() "E:/workspace/bms_vnc/vnc/utils/axios.min.map" failed (2: The system cannot find the file specified), client: 127.0.0.1, server: localhost, request: "GET /vnc/utils/axios.min.map HTTP/1.1", host: "127.0.0.1:8888"
2020/01/14 14:56:19 [error] 16388#10648: *33 CreateFile() "E:/workspace/bms_vnc/vnc/utils/axios.min.map" failed (2: The system cannot find the file specified), client: 127.0.0.1, server: localhost, request: "GET /vnc/utils/axios.min.map HTTP/1.1", host: "127.0.0.1:8888"
2020/01/14 14:57:19 [error] 16388#10648: *33 upstream timed out (10060: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond) while connecting to upstream, client: 127.0.0.1, server: localhost, request: "GET /bms/v1/vnc/ff41a86ca39044fe9fb6947e863869c8 HTTP/1.1", upstream: "http://10.13.103.43:8088/bms/v1/vnc/ff41a86ca39044fe9fb6947e863869c8", host: "127.0.0.1:8888", referrer: "http://127.0.0.1:8888/vnc/?authId=ff41a86ca39044fe9fb6947e863869c8&token=2fd11b446d275d45c4363960e55fe2513f13d422c9db50f21139b73fa5a6788c"
2020/01/14 14:57:19 [error] 16388#10648: *35 upstream timed out (10060: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond) while connecting to upstream, client: 127.0.0.1, server: localhost, request: "GET /websockify/?authId=ff41a86ca39044fe9fb6947e863869c8&token=2fd11b446d275d45c4363960e55fe2513f13d422c9db50f21139b73fa5a6788c HTTP/1.1", upstream: "http://127.0.0.1:3001/websockify/?authId=ff41a86ca39044fe9fb6947e863869c8&token=2fd11b446d275d45c4363960e55fe2513f13d422c9db50f21139b73fa5a6788c", host: "127.0.0.1:8888"
2020/01/14 15:02:00 [error] 16388#10648: *38 CreateFile() "E:/workspace/bms_vnc/vnc/utils/axios.min.map" failed (2: The system cannot find the file specified), client: 127.0.0.1, server: localhost, request: "GET /vnc/utils/axios.min.map HTTP/1.1", host: "127.0.0.1:8888"
2020/01/14 15:02:03 [error] 16388#10648: *38 CreateFile() "E:/workspace/bms_vnc/vnc/utils/axios.min.map" failed (2: The system cannot find the file specified), client: 127.0.0.1, server: localhost, request: "GET /vnc/utils/axios.min.map HTTP/1.1", host: "127.0.0.1:8888"
2020/01/14 15:03:03 [error] 16388#10648: *38 upstream timed out (10060: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond) while connecting to upstream, client: 127.0.0.1, server: localhost, request: "GET /bms/v1/vnc/6c90c590bd5f471c8af89e51cb1f4b9b HTTP/1.1", upstream: "http://10.13.103.43:8088/bms/v1/vnc/6c90c590bd5f471c8af89e51cb1f4b9b", host: "127.0.0.1:8888", referrer: "http://127.0.0.1:8888/vnc/?authId=6c90c590bd5f471c8af89e51cb1f4b9b&token=2fd11b446d275d45c4363960e55fe2516ad9103b5435bc2cc76be3a7d35e3fdd"
2020/01/14 15:03:03 [error] 16388#10648: *42 upstream timed out (10060: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond) while connecting to upstream, client: 127.0.0.1, server: localhost, request: "GET /websockify/?authId=6c90c590bd5f471c8af89e51cb1f4b9b&token=2fd11b446d275d45c4363960e55fe2516ad9103b5435bc2cc76be3a7d35e3fdd HTTP/1.1", upstream: "http://127.0.0.1:3001/websockify/?authId=6c90c590bd5f471c8af89e51cb1f4b9b&token=2fd11b446d275d45c4363960e55fe2516ad9103b5435bc2cc76be3a7d35e3fdd", host: "127.0.0.1:8888"
2020/01/14 15:10:23 [error] 16388#10648: *44 CreateFile() "E:/workspace/bms_vnc/vnc/utils/axios.min.map" failed (2: The system cannot find the file specified), client: 127.0.0.1, server: localhost, request: "GET /vnc/utils/axios.min.map HTTP/1.1", host: "127.0.0.1:8888"
2020/01/14 15:10:26 [error] 16388#10648: *44 CreateFile() "E:/workspace/bms_vnc/vnc/utils/axios.min.map" failed (2: The system cannot find the file specified), client: 127.0.0.1, server: localhost, request: "GET /vnc/utils/axios.min.map HTTP/1.1", host: "127.0.0.1:8888"
2020/01/14 15:10:31 [error] 16388#10648: *45 CreateFile() "E:/workspace/bms_vnc/vnc/utils/axios.min.map" failed (2: The system cannot find the file specified), client: 127.0.0.1, server: localhost, request: "GET /vnc/utils/axios.min.map HTTP/1.1", host: "127.0.0.1:8888"
2020/01/14 15:10:32 [error] 16388#10648: *52 CreateFile() "E:/workspace/bms_vnc/vnc/utils/axios.min.map" failed (2: The system cannot find the file specified), client: 127.0.0.1, server: localhost, request: "GET /vnc/utils/axios.min.map HTTP/1.1", host: "127.0.0.1:8888"
2020/01/14 15:11:32 [error] 16388#10648: *52 upstream timed out (10060: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond) while connecting to upstream, client: 127.0.0.1, server: localhost, request: "GET /bms/v1/vnc/6c90c590bd5f471c8af89e51cb1f4b9b HTTP/1.1", upstream: "http://10.13.103.43:8088/bms/v1/vnc/6c90c590bd5f471c8af89e51cb1f4b9b", host: "127.0.0.1:8888", referrer: "http://127.0.0.1:8888/vnc/?authId=6c90c590bd5f471c8af89e51cb1f4b9b&token=2fd11b446d275d45c4363960e55fe2516ad9103b5435bc2cc76be3a7d35e3fdd"
2020/01/14 15:11:32 [error] 16388#10648: *54 upstream timed out (10060: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond) while connecting to upstream, client: 127.0.0.1, server: localhost, request: "GET /websockify/?authId=6c90c590bd5f471c8af89e51cb1f4b9b&token=2fd11b446d275d45c4363960e55fe2516ad9103b5435bc2cc76be3a7d35e3fdd HTTP/1.1", upstream: "http://127.0.0.1:3001/websockify/?authId=6c90c590bd5f471c8af89e51cb1f4b9b&token=2fd11b446d275d45c4363960e55fe2516ad9103b5435bc2cc76be3a7d35e3fdd", host: "127.0.0.1:8888"
2020/01/14 17:19:53 [emerg] 6400#8208: invalid number of arguments in "root" directive in E:\nginx-1.9.1/conf/nginx.conf:54
2020/01/14 17:20:14 [emerg] 2672#17108: invalid number of arguments in "root" directive in E:\nginx-1.9.1/conf/nginx.conf:54
2020/01/14 17:24:03 [error] 16388#10648: *90 upstream timed out (10060: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond) while connecting to upstream, client: 127.0.0.1, server: localhost, request: "GET /bms/v1/vnc/ HTTP/1.1", upstream: "http://10.13.103.43:8088/bms/v1/vnc/", host: "127.0.0.1:8888", referrer: "http://127.0.0.1:8888/"
2020/01/14 17:25:33 [error] 7772#8420: *1 directory index of "E:/workspace/bms_op/dist" is forbidden, client: 127.0.0.1, server: localhost, request: "GET / HTTP/1.1", host: "127.0.0.1:8888"
2020/01/14 17:25:33 [error] 7772#8420: *1 directory index of "E:/workspace/bms_op/dist" is forbidden, client: 127.0.0.1, server: localhost, request: "GET / HTTP/1.1", host: "127.0.0.1:8888"
2020/01/14 17:25:34 [error] 7772#8420: *1 directory index of "E:/workspace/bms_op/dist" is forbidden, client: 127.0.0.1, server: localhost, request: "GET / HTTP/1.1", host: "127.0.0.1:8888"
2020/01/14 17:25:34 [error] 7772#8420: *1 directory index of "E:/workspace/bms_op/dist" is forbidden, client: 127.0.0.1, server: localhost, request: "GET / HTTP/1.1", host: "127.0.0.1:8888"
2020/01/14 17:25:34 [error] 7772#8420: *1 directory index of "E:/workspace/bms_op/dist" is forbidden, client: 127.0.0.1, server: localhost, request: "GET / HTTP/1.1", host: "127.0.0.1:8888"
2020/01/14 17:25:34 [error] 7772#8420: *1 directory index of "E:/workspace/bms_op/dist" is forbidden, client: 127.0.0.1, server: localhost, request: "GET / HTTP/1.1", host: "127.0.0.1:8888"
2020/01/14 17:25:35 [error] 7772#8420: *1 directory index of "E:/workspace/bms_op/dist" is forbidden, client: 127.0.0.1, server: localhost, request: "GET / HTTP/1.1", host: "127.0.0.1:8888"
2020/01/14 17:25:35 [error] 7772#8420: *1 directory index of "E:/workspace/bms_op/dist" is forbidden, client: 127.0.0.1, server: localhost, request: "GET / HTTP/1.1", host: "127.0.0.1:8888"
2020/01/14 17:25:35 [error] 7772#8420: *1 directory index of "E:/workspace/bms_op/dist" is forbidden, client: 127.0.0.1, server: localhost, request: "GET / HTTP/1.1", host: "127.0.0.1:8888"
2020/01/14 17:25:35 [error] 7772#8420: *1 directory index of "E:/workspace/bms_op/dist" is forbidden, client: 127.0.0.1, server: localhost, request: "GET / HTTP/1.1", host: "127.0.0.1:8888"
2020/01/14 17:26:29 [error] 7772#8420: *1 directory index of "E:/workspace/bms_op/dist" is forbidden, client: 127.0.0.1, server: localhost, request: "GET / HTTP/1.1", host: "127.0.0.1:8888"
2020/01/14 17:26:30 [error] 7772#8420: *1 directory index of "E:/workspace/bms_op/dist" is forbidden, client: 127.0.0.1, server: localhost, request: "GET / HTTP/1.1", host: "127.0.0.1:8888"
2020/01/14 17:26:30 [error] 7772#8420: *1 directory index of "E:/workspace/bms_op/dist" is forbidden, client: 127.0.0.1, server: localhost, request: "GET / HTTP/1.1", host: "127.0.0.1:8888"
2020/01/14 17:26:30 [error] 7772#8420: *1 directory index of "E:/workspace/bms_op/dist" is forbidden, client: 127.0.0.1, server: localhost, request: "GET / HTTP/1.1", host: "127.0.0.1:8888"
2020/01/14 17:26:30 [error] 7772#8420: *1 directory index of "E:/workspace/bms_op/dist" is forbidden, client: 127.0.0.1, server: localhost, request: "GET / HTTP/1.1", host: "127.0.0.1:8888"
2020/01/14 17:26:30 [error] 7772#8420: *1 directory index of "E:/workspace/bms_op/dist" is forbidden, client: 127.0.0.1, server: localhost, request: "GET / HTTP/1.1", host: "127.0.0.1:8888"
